//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class sespAdmision {
    
    /// <summary>
    /// lblTipoPerfil control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblTipoPerfil;
    
    /// <summary>
    /// wucDatosPersonales control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::wucDatosPersonales wucDatosPersonales;
    
    /// <summary>
    /// wucOtrosDatos control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ley22_WebApp_V2.wucOtrosDatos wucOtrosDatos;
    
    /// <summary>
    /// wucDatosDemograficos control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ley22_WebApp_V2.wucDatosDemograficos wucDatosDemograficos;
    
    /// <summary>
    /// wucEpisodioAdmision control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ley22_WebApp_V2.wucEpisodioAdmision wucEpisodioAdmision;
    
    /// <summary>
    /// wucDatosAdmision control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ley22_WebApp_V2.wucDatosAdmision wucDatosAdmision;
}
