//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ley22_WebApp_V2.Old_App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendario
    {
        public int Id_Calendario { get; set; }
        public string Id_TrabajadorSocial { get; set; }
        public System.DateTime FechadeSolicitud { get; set; }
        public int Id_Participante { get; set; }
        public System.DateTime FechaInicial { get; set; }
        public System.DateTime FechaFinal { get; set; }
        public int Id_OrdenJudicial { get; set; }
        public int Asistio { get; set; }
    }
}
