//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ley22_WebApp_V2.Old_App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharlaGrupal
    {
        public int Id_CharlaGrupal { get; set; }
        public int Id_Centro { get; set; }
        public System.DateTime FechaInicial { get; set; }
        public System.DateTime FechaFinal { get; set; }
        public int Id_TipoCharla { get; set; }
        public int Id_Nivel { get; set; }
        public int NrodeParticipantes { get; set; }
        public string Id_Usuario { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> NumeroCharla { get; set; }
    }
}
