//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ley22_WebApp_V2.Old_App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControldePago
    {
        public int Id_ControldePagos { get; set; }
        public int Id_Participante { get; set; }
        public int Id_Precio { get; set; }
        public int Id_FormadePago { get; set; }
        public Nullable<int> NumerodeCheque { get; set; }
        public Nullable<System.DateTime> FechadelPago { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<int> Estatus { get; set; }
        public string Id_Usuario { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<int> Id_Calendario { get; set; }
        public Nullable<int> Id_CharlaGrupal { get; set; }
        public Nullable<int> Id_OrdenJudicial { get; set; }
        public string NumeroRecibo { get; set; }
    }
}
