//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ley22_WebApp_V2.Old_App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControldePago
    {
        public int PK_ControldePago { get; set; }
        public int FK_CasoCriminal { get; set; }
        public Nullable<int> FK_Calendario { get; set; }
        public Nullable<int> FK_CharlaGrupal { get; set; }
        public string FK_Usuario { get; set; }
        public System.DateTime FechaTransaccion { get; set; }
        public string TipoTransaccion { get; set; }
        public int FK_FormadePago { get; set; }
        public decimal Cantidad { get; set; }
        public string Descripcion { get; set; }
        public string NumeroRecibo { get; set; }
        public Nullable<long> NumerodeCheque { get; set; }
        public string VoidDesc { get; set; }
    }
}
