//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ley22_WebApp_V2.Old_App_Code
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Ley22Entities : DbContext
    {
        public Ley22Entities()
            : base("name=Ley22Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Centro> Centros { get; set; }
        public virtual DbSet<CharlaGrupal> CharlaGrupals { get; set; }
        public virtual DbSet<Ciudad> Ciudads { get; set; }
        public virtual DbSet<ControldePago> ControldePagos { get; set; }
        public virtual DbSet<Documento> Documentos { get; set; }
        public virtual DbSet<DocumentosPorParticipante> DocumentosPorParticipantes { get; set; }
        public virtual DbSet<FormadePago> FormadePagoes { get; set; }
        public virtual DbSet<MotivoCierre> MotivoCierres { get; set; }
        public virtual DbSet<NivelesdelasCharla> NivelesdelasCharlas { get; set; }
        public virtual DbSet<OrdenesJudiciale> OrdenesJudiciales { get; set; }
        public virtual DbSet<Participante> Participantes { get; set; }
        public virtual DbSet<ParticipantesPorCharla> ParticipantesPorCharlas { get; set; }
        public virtual DbSet<Precio> Precios { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<SA_PERSONA> SA_PERSONA { get; set; }
        public virtual DbSet<TipodeCharla> TipodeCharlas { get; set; }
        public virtual DbSet<TrabajadorSocial> TrabajadorSocials { get; set; }
        public virtual DbSet<TS_Excepciones> TS_Excepciones { get; set; }
        public virtual DbSet<Programas_Region_Mapping> Programas_Region_Mapping { get; set; }
        public virtual DbSet<CCG_Excepciones> CCG_Excepciones { get; set; }
        public virtual DbSet<PERMISO> PERMISOes { get; set; }
        public virtual DbSet<SA_USUARIO_PERMISO_Mapping> SA_USUARIO_PERMISO_Mapping { get; set; }
        public virtual DbSet<USUARIO_PROGRAMA> USUARIO_PROGRAMA { get; set; }
        public virtual DbSet<Calendario> Calendarios { get; set; }
    
        public virtual ObjectResult<BuscarSEPSPersonaXNroSeguroSocial_Result> BuscarSEPSPersonaXNroSeguroSocial(string nR_SeguroSocial)
        {
            var nR_SeguroSocialParameter = nR_SeguroSocial != null ?
                new ObjectParameter("NR_SeguroSocial", nR_SeguroSocial) :
                new ObjectParameter("NR_SeguroSocial", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BuscarSEPSPersonaXNroSeguroSocial_Result>("BuscarSEPSPersonaXNroSeguroSocial", nR_SeguroSocialParameter);
        }
    
        public virtual ObjectResult<BusquedaSencilladePersonas_Result> BusquedaSencilladePersonas(string nR_SeguroSocial, string identificacion, Nullable<System.DateTime> fE_Nacimiento, string nombreApellido)
        {
            var nR_SeguroSocialParameter = nR_SeguroSocial != null ?
                new ObjectParameter("NR_SeguroSocial", nR_SeguroSocial) :
                new ObjectParameter("NR_SeguroSocial", typeof(string));
    
            var identificacionParameter = identificacion != null ?
                new ObjectParameter("Identificacion", identificacion) :
                new ObjectParameter("Identificacion", typeof(string));
    
            var fE_NacimientoParameter = fE_Nacimiento.HasValue ?
                new ObjectParameter("FE_Nacimiento", fE_Nacimiento) :
                new ObjectParameter("FE_Nacimiento", typeof(System.DateTime));
    
            var nombreApellidoParameter = nombreApellido != null ?
                new ObjectParameter("NombreApellido", nombreApellido) :
                new ObjectParameter("NombreApellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BusquedaSencilladePersonas_Result>("BusquedaSencilladePersonas", nR_SeguroSocialParameter, identificacionParameter, fE_NacimientoParameter, nombreApellidoParameter);
        }
    
        public virtual int CerrarordenJudicial(Nullable<int> id_OrdenJudicial, Nullable<int> id_MotivoCierre, string comentarioCierre, string documentoAprobacion, Nullable<int> id_UsuarioCierre)
        {
            var id_OrdenJudicialParameter = id_OrdenJudicial.HasValue ?
                new ObjectParameter("Id_OrdenJudicial", id_OrdenJudicial) :
                new ObjectParameter("Id_OrdenJudicial", typeof(int));
    
            var id_MotivoCierreParameter = id_MotivoCierre.HasValue ?
                new ObjectParameter("Id_MotivoCierre", id_MotivoCierre) :
                new ObjectParameter("Id_MotivoCierre", typeof(int));
    
            var comentarioCierreParameter = comentarioCierre != null ?
                new ObjectParameter("ComentarioCierre", comentarioCierre) :
                new ObjectParameter("ComentarioCierre", typeof(string));
    
            var documentoAprobacionParameter = documentoAprobacion != null ?
                new ObjectParameter("DocumentoAprobacion", documentoAprobacion) :
                new ObjectParameter("DocumentoAprobacion", typeof(string));
    
            var id_UsuarioCierreParameter = id_UsuarioCierre.HasValue ?
                new ObjectParameter("Id_UsuarioCierre", id_UsuarioCierre) :
                new ObjectParameter("Id_UsuarioCierre", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CerrarordenJudicial", id_OrdenJudicialParameter, id_MotivoCierreParameter, comentarioCierreParameter, documentoAprobacionParameter, id_UsuarioCierreParameter);
        }
    
        public virtual ObjectResult<ConsultarCharlasPorParticipante_Result> ConsultarCharlasPorParticipante(Nullable<int> id_Participante)
        {
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarCharlasPorParticipante_Result>("ConsultarCharlasPorParticipante", id_ParticipanteParameter);
        }
    
        public virtual ObjectResult<ConsultarEpisodiosXPersona_Result> ConsultarEpisodiosXPersona(Nullable<int> pk_Persona)
        {
            var pk_PersonaParameter = pk_Persona.HasValue ?
                new ObjectParameter("Pk_Persona", pk_Persona) :
                new ObjectParameter("Pk_Persona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarEpisodiosXPersona_Result>("ConsultarEpisodiosXPersona", pk_PersonaParameter);
        }
    
        public virtual ObjectResult<DetalleCharlaGrupal_Result> DetalleCharlaGrupal(Nullable<int> id_CharlaGrupal)
        {
            var id_CharlaGrupalParameter = id_CharlaGrupal.HasValue ?
                new ObjectParameter("Id_CharlaGrupal", id_CharlaGrupal) :
                new ObjectParameter("Id_CharlaGrupal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DetalleCharlaGrupal_Result>("DetalleCharlaGrupal", id_CharlaGrupalParameter);
        }
    
        public virtual int EliminarCharlaGrupal(Nullable<int> id_CharlaGrupal)
        {
            var id_CharlaGrupalParameter = id_CharlaGrupal.HasValue ?
                new ObjectParameter("Id_CharlaGrupal", id_CharlaGrupal) :
                new ObjectParameter("Id_CharlaGrupal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarCharlaGrupal", id_CharlaGrupalParameter);
        }
    
        public virtual int EliminarCitaTrabajadorSocial(Nullable<int> id_Calendario)
        {
            var id_CalendarioParameter = id_Calendario.HasValue ?
                new ObjectParameter("Id_Calendario", id_Calendario) :
                new ObjectParameter("Id_Calendario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarCitaTrabajadorSocial", id_CalendarioParameter);
        }
    
        public virtual int EliminarDocuemntoPorParticipante(Nullable<int> id_DocumentoPorParticipante)
        {
            var id_DocumentoPorParticipanteParameter = id_DocumentoPorParticipante.HasValue ?
                new ObjectParameter("Id_DocumentoPorParticipante", id_DocumentoPorParticipante) :
                new ObjectParameter("Id_DocumentoPorParticipante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarDocuemntoPorParticipante", id_DocumentoPorParticipanteParameter);
        }
    
        public virtual int EliminarParticipanteCharlaGrupal(Nullable<int> id_CharlaGrupal, Nullable<int> id_Participante)
        {
            var id_CharlaGrupalParameter = id_CharlaGrupal.HasValue ?
                new ObjectParameter("Id_CharlaGrupal", id_CharlaGrupal) :
                new ObjectParameter("Id_CharlaGrupal", typeof(int));
    
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarParticipanteCharlaGrupal", id_CharlaGrupalParameter, id_ParticipanteParameter);
        }
    
        public virtual int GuardarCharlaGrupal(Nullable<int> id_Centro, Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal, Nullable<int> id_TipoCharla, Nullable<int> id_Nivel, Nullable<int> nrodeParticipantes, Nullable<int> id_Usuario)
        {
            var id_CentroParameter = id_Centro.HasValue ?
                new ObjectParameter("Id_Centro", id_Centro) :
                new ObjectParameter("Id_Centro", typeof(int));
    
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("FechaInicial", fechaInicial) :
                new ObjectParameter("FechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            var id_TipoCharlaParameter = id_TipoCharla.HasValue ?
                new ObjectParameter("Id_TipoCharla", id_TipoCharla) :
                new ObjectParameter("Id_TipoCharla", typeof(int));
    
            var id_NivelParameter = id_Nivel.HasValue ?
                new ObjectParameter("Id_Nivel", id_Nivel) :
                new ObjectParameter("Id_Nivel", typeof(int));
    
            var nrodeParticipantesParameter = nrodeParticipantes.HasValue ?
                new ObjectParameter("NrodeParticipantes", nrodeParticipantes) :
                new ObjectParameter("NrodeParticipantes", typeof(int));
    
            var id_UsuarioParameter = id_Usuario.HasValue ?
                new ObjectParameter("Id_Usuario", id_Usuario) :
                new ObjectParameter("Id_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarCharlaGrupal", id_CentroParameter, fechaInicialParameter, fechaFinalParameter, id_TipoCharlaParameter, id_NivelParameter, nrodeParticipantesParameter, id_UsuarioParameter);
        }
    
        public virtual int GuardarDocumentoPorParticipante(Nullable<int> id_Documento, Nullable<int> id_Participante, Nullable<int> id_OrdenJudicial, string pathNameDocumento, Nullable<int> id_UsuarioRecibe)
        {
            var id_DocumentoParameter = id_Documento.HasValue ?
                new ObjectParameter("Id_Documento", id_Documento) :
                new ObjectParameter("Id_Documento", typeof(int));
    
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            var id_OrdenJudicialParameter = id_OrdenJudicial.HasValue ?
                new ObjectParameter("Id_OrdenJudicial", id_OrdenJudicial) :
                new ObjectParameter("Id_OrdenJudicial", typeof(int));
    
            var pathNameDocumentoParameter = pathNameDocumento != null ?
                new ObjectParameter("PathNameDocumento", pathNameDocumento) :
                new ObjectParameter("PathNameDocumento", typeof(string));
    
            var id_UsuarioRecibeParameter = id_UsuarioRecibe.HasValue ?
                new ObjectParameter("Id_UsuarioRecibe", id_UsuarioRecibe) :
                new ObjectParameter("Id_UsuarioRecibe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarDocumentoPorParticipante", id_DocumentoParameter, id_ParticipanteParameter, id_OrdenJudicialParameter, pathNameDocumentoParameter, id_UsuarioRecibeParameter);
        }
    
        public virtual int GuardarOrdenJudicial(Nullable<int> id_Participante, string numeroOrdenJudicial, Nullable<int> id_UsuarioCreacion)
        {
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            var numeroOrdenJudicialParameter = numeroOrdenJudicial != null ?
                new ObjectParameter("NumeroOrdenJudicial", numeroOrdenJudicial) :
                new ObjectParameter("NumeroOrdenJudicial", typeof(string));
    
            var id_UsuarioCreacionParameter = id_UsuarioCreacion.HasValue ?
                new ObjectParameter("Id_UsuarioCreacion", id_UsuarioCreacion) :
                new ObjectParameter("Id_UsuarioCreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarOrdenJudicial", id_ParticipanteParameter, numeroOrdenJudicialParameter, id_UsuarioCreacionParameter);
        }
    
        public virtual int GuardarParticipantePorCharlas(Nullable<int> id_CharlaGrupal, Nullable<int> id_Participante, Nullable<int> id_Usuario, Nullable<int> id_OrdenJudicial)
        {
            var id_CharlaGrupalParameter = id_CharlaGrupal.HasValue ?
                new ObjectParameter("Id_CharlaGrupal", id_CharlaGrupal) :
                new ObjectParameter("Id_CharlaGrupal", typeof(int));
    
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            var id_UsuarioParameter = id_Usuario.HasValue ?
                new ObjectParameter("Id_Usuario", id_Usuario) :
                new ObjectParameter("Id_Usuario", typeof(int));
    
            var id_OrdenJudicialParameter = id_OrdenJudicial.HasValue ?
                new ObjectParameter("Id_OrdenJudicial", id_OrdenJudicial) :
                new ObjectParameter("Id_OrdenJudicial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarParticipantePorCharlas", id_CharlaGrupalParameter, id_ParticipanteParameter, id_UsuarioParameter, id_OrdenJudicialParameter);
        }
    
        public virtual ObjectResult<ListarBalancedePagos_Result> ListarBalancedePagos(Nullable<int> id_Participante, Nullable<int> id_OrdenJudicial)
        {
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            var id_OrdenJudicialParameter = id_OrdenJudicial.HasValue ?
                new ObjectParameter("Id_OrdenJudicial", id_OrdenJudicial) :
                new ObjectParameter("Id_OrdenJudicial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarBalancedePagos_Result>("ListarBalancedePagos", id_ParticipanteParameter, id_OrdenJudicialParameter);
        }
    
        public virtual ObjectResult<ListarCharlasCalendario_Result> ListarCharlasCalendario(Nullable<int> id_Centro, Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal)
        {
            var id_CentroParameter = id_Centro.HasValue ?
                new ObjectParameter("Id_Centro", id_Centro) :
                new ObjectParameter("Id_Centro", typeof(int));
    
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("fechaInicial", fechaInicial) :
                new ObjectParameter("fechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarCharlasCalendario_Result>("ListarCharlasCalendario", id_CentroParameter, fechaInicialParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<ListarCitasCalendario_Result> ListarCitasCalendario(string id_TrabajadorSocial, Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal)
        {
            var id_TrabajadorSocialParameter = id_TrabajadorSocial != null ?
                new ObjectParameter("Id_TrabajadorSocial", id_TrabajadorSocial) :
                new ObjectParameter("Id_TrabajadorSocial", typeof(string));
    
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("fechaInicial", fechaInicial) :
                new ObjectParameter("fechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarCitasCalendario_Result>("ListarCitasCalendario", id_TrabajadorSocialParameter, fechaInicialParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<ListarDocumentosActivos_Result> ListarDocumentosActivos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarDocumentosActivos_Result>("ListarDocumentosActivos");
        }
    
        public virtual ObjectResult<ListarDocumentosRecibidos_Result> ListarDocumentosRecibidos(Nullable<int> id_Participante)
        {
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarDocumentosRecibidos_Result>("ListarDocumentosRecibidos", id_ParticipanteParameter);
        }
    
        public virtual ObjectResult<ListarMotivosCierre_Result> ListarMotivosCierre()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarMotivosCierre_Result>("ListarMotivosCierre");
        }
    
        public virtual ObjectResult<ListarOrdenesJudicialesActivas_Result> ListarOrdenesJudicialesActivas(Nullable<int> id_Participante)
        {
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarOrdenesJudicialesActivas_Result>("ListarOrdenesJudicialesActivas", id_ParticipanteParameter);
        }
    
        public virtual ObjectResult<ListarParticipantesPorCharlas_Result> ListarParticipantesPorCharlas(Nullable<int> id_CharlaGrupal)
        {
            var id_CharlaGrupalParameter = id_CharlaGrupal.HasValue ?
                new ObjectParameter("Id_CharlaGrupal", id_CharlaGrupal) :
                new ObjectParameter("Id_CharlaGrupal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarParticipantesPorCharlas_Result>("ListarParticipantesPorCharlas", id_CharlaGrupalParameter);
        }
    
        public virtual ObjectResult<ListarTipodeDocumentosPorParticipanteOrdenJudicial_Result> ListarTipodeDocumentosPorParticipanteOrdenJudicial(Nullable<int> id_OrdenJudicial, Nullable<int> id_Participante)
        {
            var id_OrdenJudicialParameter = id_OrdenJudicial.HasValue ?
                new ObjectParameter("Id_OrdenJudicial", id_OrdenJudicial) :
                new ObjectParameter("Id_OrdenJudicial", typeof(int));
    
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarTipodeDocumentosPorParticipanteOrdenJudicial_Result>("ListarTipodeDocumentosPorParticipanteOrdenJudicial", id_OrdenJudicialParameter, id_ParticipanteParameter);
        }
    
        public virtual int RegistrarPago(Nullable<int> id_ControldePagos, Nullable<decimal> cantidad, Nullable<int> id_FormadePago, Nullable<int> numerodeCheque, Nullable<System.DateTime> fechadelPago, Nullable<int> id_Usuario)
        {
            var id_ControldePagosParameter = id_ControldePagos.HasValue ?
                new ObjectParameter("Id_ControldePagos", id_ControldePagos) :
                new ObjectParameter("Id_ControldePagos", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(decimal));
    
            var id_FormadePagoParameter = id_FormadePago.HasValue ?
                new ObjectParameter("Id_FormadePago", id_FormadePago) :
                new ObjectParameter("Id_FormadePago", typeof(int));
    
            var numerodeChequeParameter = numerodeCheque.HasValue ?
                new ObjectParameter("NumerodeCheque", numerodeCheque) :
                new ObjectParameter("NumerodeCheque", typeof(int));
    
            var fechadelPagoParameter = fechadelPago.HasValue ?
                new ObjectParameter("FechadelPago", fechadelPago) :
                new ObjectParameter("FechadelPago", typeof(System.DateTime));
    
            var id_UsuarioParameter = id_Usuario.HasValue ?
                new ObjectParameter("Id_Usuario", id_Usuario) :
                new ObjectParameter("Id_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegistrarPago", id_ControldePagosParameter, cantidadParameter, id_FormadePagoParameter, numerodeChequeParameter, fechadelPagoParameter, id_UsuarioParameter);
        }
    
        public virtual ObjectResult<ResumendeAsistenciasCharlas_Result> ResumendeAsistenciasCharlas(Nullable<int> id_Participante)
        {
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ResumendeAsistenciasCharlas_Result>("ResumendeAsistenciasCharlas", id_ParticipanteParameter);
        }
    
        public virtual ObjectResult<Sp_Read_CalendariobyId_Result> Sp_Read_CalendariobyId(Nullable<int> id_Participante)
        {
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Read_CalendariobyId_Result>("Sp_Read_CalendariobyId", id_ParticipanteParameter);
        }
    
        public virtual ObjectResult<sp_READ_CentrobyRegion_Result> sp_READ_CentrobyRegion(Nullable<int> id_Region)
        {
            var id_RegionParameter = id_Region.HasValue ?
                new ObjectParameter("Id_Region", id_Region) :
                new ObjectParameter("Id_Region", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_READ_CentrobyRegion_Result>("sp_READ_CentrobyRegion", id_RegionParameter);
        }
    
        public virtual ObjectResult<sp_READ_ParticipantesxId_Result> sp_READ_ParticipantesxId(Nullable<int> id_Participante)
        {
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_READ_ParticipantesxId_Result>("sp_READ_ParticipantesxId", id_ParticipanteParameter);
        }
    
        public virtual ObjectResult<sp_READ_SA_PERSONAxId_Result> sp_READ_SA_PERSONAxId(Nullable<int> id_Participante, Nullable<int> pk_Persona)
        {
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            var pk_PersonaParameter = pk_Persona.HasValue ?
                new ObjectParameter("Pk_Persona", pk_Persona) :
                new ObjectParameter("Pk_Persona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_READ_SA_PERSONAxId_Result>("sp_READ_SA_PERSONAxId", id_ParticipanteParameter, pk_PersonaParameter);
        }
    
        public virtual ObjectResult<sp_READ_TrabajadorSocialbyCentro_Result> sp_READ_TrabajadorSocialbyCentro(Nullable<int> id_Centro)
        {
            var id_CentroParameter = id_Centro.HasValue ?
                new ObjectParameter("Id_Centro", id_Centro) :
                new ObjectParameter("Id_Centro", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_READ_TrabajadorSocialbyCentro_Result>("sp_READ_TrabajadorSocialbyCentro", id_CentroParameter);
        }
    
        public virtual ObjectResult<sp_READALL_Ciudad_Result> sp_READALL_Ciudad(Nullable<int> id_Region)
        {
            var id_RegionParameter = id_Region.HasValue ?
                new ObjectParameter("Id_Region", id_Region) :
                new ObjectParameter("Id_Region", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_READALL_Ciudad_Result>("sp_READALL_Ciudad", id_RegionParameter);
        }
    
        public virtual ObjectResult<sp_READALL_NivelesdelasCharlas_Result> sp_READALL_NivelesdelasCharlas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_READALL_NivelesdelasCharlas_Result>("sp_READALL_NivelesdelasCharlas");
        }
    
        public virtual ObjectResult<sp_READALL_Regiones_Result> sp_READALL_Regiones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_READALL_Regiones_Result>("sp_READALL_Regiones");
        }
    
        public virtual ObjectResult<sp_READALL_TipodeCharlas_Result> sp_READALL_TipodeCharlas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_READALL_TipodeCharlas_Result>("sp_READALL_TipodeCharlas");
        }
    
        public virtual ObjectResult<Nullable<int>> SPC_Persona(string nR_SeguroSocial, string identificacion, string pasaporte, string licencia, Nullable<int> iUP, string expediente, string nB_Primero, string nB_Segundo, string aP_Primero, string aP_Segundo, Nullable<System.DateTime> fE_Nacimiento, Nullable<byte> fK_Sexo, Nullable<byte> fK_GrupoEtnico, Nullable<byte> fK_Veterano, string correo, string telefono1, string telefono2, string telefonoFamiliarMasCercano, string telefonoCitas, string direccionLinea1, string direccionLinea2, string municipio, string codigoPostal, Nullable<int> fk_UsuarioEdicion, Nullable<int> id_Participante)
        {
            var nR_SeguroSocialParameter = nR_SeguroSocial != null ?
                new ObjectParameter("NR_SeguroSocial", nR_SeguroSocial) :
                new ObjectParameter("NR_SeguroSocial", typeof(string));
    
            var identificacionParameter = identificacion != null ?
                new ObjectParameter("Identificacion", identificacion) :
                new ObjectParameter("Identificacion", typeof(string));
    
            var pasaporteParameter = pasaporte != null ?
                new ObjectParameter("Pasaporte", pasaporte) :
                new ObjectParameter("Pasaporte", typeof(string));
    
            var licenciaParameter = licencia != null ?
                new ObjectParameter("Licencia", licencia) :
                new ObjectParameter("Licencia", typeof(string));
    
            var iUPParameter = iUP.HasValue ?
                new ObjectParameter("IUP", iUP) :
                new ObjectParameter("IUP", typeof(int));
    
            var expedienteParameter = expediente != null ?
                new ObjectParameter("Expediente", expediente) :
                new ObjectParameter("Expediente", typeof(string));
    
            var nB_PrimeroParameter = nB_Primero != null ?
                new ObjectParameter("NB_Primero", nB_Primero) :
                new ObjectParameter("NB_Primero", typeof(string));
    
            var nB_SegundoParameter = nB_Segundo != null ?
                new ObjectParameter("NB_Segundo", nB_Segundo) :
                new ObjectParameter("NB_Segundo", typeof(string));
    
            var aP_PrimeroParameter = aP_Primero != null ?
                new ObjectParameter("AP_Primero", aP_Primero) :
                new ObjectParameter("AP_Primero", typeof(string));
    
            var aP_SegundoParameter = aP_Segundo != null ?
                new ObjectParameter("AP_Segundo", aP_Segundo) :
                new ObjectParameter("AP_Segundo", typeof(string));
    
            var fE_NacimientoParameter = fE_Nacimiento.HasValue ?
                new ObjectParameter("FE_Nacimiento", fE_Nacimiento) :
                new ObjectParameter("FE_Nacimiento", typeof(System.DateTime));
    
            var fK_SexoParameter = fK_Sexo.HasValue ?
                new ObjectParameter("FK_Sexo", fK_Sexo) :
                new ObjectParameter("FK_Sexo", typeof(byte));
    
            var fK_GrupoEtnicoParameter = fK_GrupoEtnico.HasValue ?
                new ObjectParameter("FK_GrupoEtnico", fK_GrupoEtnico) :
                new ObjectParameter("FK_GrupoEtnico", typeof(byte));
    
            var fK_VeteranoParameter = fK_Veterano.HasValue ?
                new ObjectParameter("FK_Veterano", fK_Veterano) :
                new ObjectParameter("FK_Veterano", typeof(byte));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var telefono1Parameter = telefono1 != null ?
                new ObjectParameter("Telefono1", telefono1) :
                new ObjectParameter("Telefono1", typeof(string));
    
            var telefono2Parameter = telefono2 != null ?
                new ObjectParameter("Telefono2", telefono2) :
                new ObjectParameter("Telefono2", typeof(string));
    
            var telefonoFamiliarMasCercanoParameter = telefonoFamiliarMasCercano != null ?
                new ObjectParameter("TelefonoFamiliarMasCercano", telefonoFamiliarMasCercano) :
                new ObjectParameter("TelefonoFamiliarMasCercano", typeof(string));
    
            var telefonoCitasParameter = telefonoCitas != null ?
                new ObjectParameter("TelefonoCitas", telefonoCitas) :
                new ObjectParameter("TelefonoCitas", typeof(string));
    
            var direccionLinea1Parameter = direccionLinea1 != null ?
                new ObjectParameter("DireccionLinea1", direccionLinea1) :
                new ObjectParameter("DireccionLinea1", typeof(string));
    
            var direccionLinea2Parameter = direccionLinea2 != null ?
                new ObjectParameter("DireccionLinea2", direccionLinea2) :
                new ObjectParameter("DireccionLinea2", typeof(string));
    
            var municipioParameter = municipio != null ?
                new ObjectParameter("Municipio", municipio) :
                new ObjectParameter("Municipio", typeof(string));
    
            var codigoPostalParameter = codigoPostal != null ?
                new ObjectParameter("CodigoPostal", codigoPostal) :
                new ObjectParameter("CodigoPostal", typeof(string));
    
            var fk_UsuarioEdicionParameter = fk_UsuarioEdicion.HasValue ?
                new ObjectParameter("Fk_UsuarioEdicion", fk_UsuarioEdicion) :
                new ObjectParameter("Fk_UsuarioEdicion", typeof(int));
    
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SPC_Persona", nR_SeguroSocialParameter, identificacionParameter, pasaporteParameter, licenciaParameter, iUPParameter, expedienteParameter, nB_PrimeroParameter, nB_SegundoParameter, aP_PrimeroParameter, aP_SegundoParameter, fE_NacimientoParameter, fK_SexoParameter, fK_GrupoEtnicoParameter, fK_VeteranoParameter, correoParameter, telefono1Parameter, telefono2Parameter, telefonoFamiliarMasCercanoParameter, telefonoCitasParameter, direccionLinea1Parameter, direccionLinea2Parameter, municipioParameter, codigoPostalParameter, fk_UsuarioEdicionParameter, id_ParticipanteParameter);
        }
    
        public virtual int AsignaCitaTrabajadorSocial(Nullable<int> id_TrabajadorSocial, Nullable<int> pK_Ley22, Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal, Nullable<int> id_OrdenJudicial)
        {
            var id_TrabajadorSocialParameter = id_TrabajadorSocial.HasValue ?
                new ObjectParameter("Id_TrabajadorSocial", id_TrabajadorSocial) :
                new ObjectParameter("Id_TrabajadorSocial", typeof(int));
    
            var pK_Ley22Parameter = pK_Ley22.HasValue ?
                new ObjectParameter("PK_Ley22", pK_Ley22) :
                new ObjectParameter("PK_Ley22", typeof(int));
    
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("FechaInicial", fechaInicial) :
                new ObjectParameter("FechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            var id_OrdenJudicialParameter = id_OrdenJudicial.HasValue ?
                new ObjectParameter("Id_OrdenJudicial", id_OrdenJudicial) :
                new ObjectParameter("Id_OrdenJudicial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AsignaCitaTrabajadorSocial", id_TrabajadorSocialParameter, pK_Ley22Parameter, fechaInicialParameter, fechaFinalParameter, id_OrdenJudicialParameter);
        }
    
        public virtual int ListarCalendario(Nullable<int> id_TrabajadorSocial)
        {
            var id_TrabajadorSocialParameter = id_TrabajadorSocial.HasValue ?
                new ObjectParameter("Id_TrabajadorSocial", id_TrabajadorSocial) :
                new ObjectParameter("Id_TrabajadorSocial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListarCalendario", id_TrabajadorSocialParameter);
        }
    
        public virtual ObjectResult<InfoCharlaGrupal_Result> InfoCharlaGrupal(Nullable<int> id_CharlaGrupal)
        {
            var id_CharlaGrupalParameter = id_CharlaGrupal.HasValue ?
                new ObjectParameter("Id_CharlaGrupal", id_CharlaGrupal) :
                new ObjectParameter("Id_CharlaGrupal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InfoCharlaGrupal_Result>("InfoCharlaGrupal", id_CharlaGrupalParameter);
        }
    
        public virtual int ModificarCharlaGrupal(Nullable<int> id_CharlaGrupal, Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal, Nullable<int> id_TipoCharla, Nullable<int> id_Nivel, Nullable<int> nrodeParticipantes, Nullable<int> id_Usuario)
        {
            var id_CharlaGrupalParameter = id_CharlaGrupal.HasValue ?
                new ObjectParameter("Id_CharlaGrupal", id_CharlaGrupal) :
                new ObjectParameter("Id_CharlaGrupal", typeof(int));
    
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("FechaInicial", fechaInicial) :
                new ObjectParameter("FechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            var id_TipoCharlaParameter = id_TipoCharla.HasValue ?
                new ObjectParameter("Id_TipoCharla", id_TipoCharla) :
                new ObjectParameter("Id_TipoCharla", typeof(int));
    
            var id_NivelParameter = id_Nivel.HasValue ?
                new ObjectParameter("Id_Nivel", id_Nivel) :
                new ObjectParameter("Id_Nivel", typeof(int));
    
            var nrodeParticipantesParameter = nrodeParticipantes.HasValue ?
                new ObjectParameter("NrodeParticipantes", nrodeParticipantes) :
                new ObjectParameter("NrodeParticipantes", typeof(int));
    
            var id_UsuarioParameter = id_Usuario.HasValue ?
                new ObjectParameter("Id_Usuario", id_Usuario) :
                new ObjectParameter("Id_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModificarCharlaGrupal", id_CharlaGrupalParameter, fechaInicialParameter, fechaFinalParameter, id_TipoCharlaParameter, id_NivelParameter, nrodeParticipantesParameter, id_UsuarioParameter);
        }
    
        public virtual ObjectResult<ListarExcepcionesTrabajadorSocial_Result> ListarExcepcionesTrabajadorSocial(string id_TrabajadorSocial, Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal)
        {
            var id_TrabajadorSocialParameter = id_TrabajadorSocial != null ?
                new ObjectParameter("Id_TrabajadorSocial", id_TrabajadorSocial) :
                new ObjectParameter("Id_TrabajadorSocial", typeof(string));
    
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("fechaInicial", fechaInicial) :
                new ObjectParameter("fechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarExcepcionesTrabajadorSocial_Result>("ListarExcepcionesTrabajadorSocial", id_TrabajadorSocialParameter, fechaInicialParameter, fechaFinalParameter);
        }
    
        public virtual int GuardarExcepcionCoordinadorCharlasGrupales(Nullable<int> id_Centro, Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal)
        {
            var id_CentroParameter = id_Centro.HasValue ?
                new ObjectParameter("Id_Centro", id_Centro) :
                new ObjectParameter("Id_Centro", typeof(int));
    
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("FechaInicial", fechaInicial) :
                new ObjectParameter("FechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarExcepcionCoordinadorCharlasGrupales", id_CentroParameter, fechaInicialParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<ListarExcepcionesCharlaGrupal_Result> ListarExcepcionesCharlaGrupal(Nullable<int> id_Centro, Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal)
        {
            var id_CentroParameter = id_Centro.HasValue ?
                new ObjectParameter("Id_Centro", id_Centro) :
                new ObjectParameter("Id_Centro", typeof(int));
    
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("fechaInicial", fechaInicial) :
                new ObjectParameter("fechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarExcepcionesCharlaGrupal_Result>("ListarExcepcionesCharlaGrupal", id_CentroParameter, fechaInicialParameter, fechaFinalParameter);
        }
    
        public virtual int GuardarCitaTrabajadorSocial(string id_TrabajadorSocial, Nullable<int> id_Participante, Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal, Nullable<int> id_OrdenJudicial, Nullable<int> id_Programa)
        {
            var id_TrabajadorSocialParameter = id_TrabajadorSocial != null ?
                new ObjectParameter("Id_TrabajadorSocial", id_TrabajadorSocial) :
                new ObjectParameter("Id_TrabajadorSocial", typeof(string));
    
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("FechaInicial", fechaInicial) :
                new ObjectParameter("FechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            var id_OrdenJudicialParameter = id_OrdenJudicial.HasValue ?
                new ObjectParameter("Id_OrdenJudicial", id_OrdenJudicial) :
                new ObjectParameter("Id_OrdenJudicial", typeof(int));
    
            var id_ProgramaParameter = id_Programa.HasValue ?
                new ObjectParameter("Id_Programa", id_Programa) :
                new ObjectParameter("Id_Programa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarCitaTrabajadorSocial", id_TrabajadorSocialParameter, id_ParticipanteParameter, fechaInicialParameter, fechaFinalParameter, id_OrdenJudicialParameter, id_ProgramaParameter);
        }
    
        public virtual ObjectResult<ListarCitasCalendarioUsuario_Result> ListarCitasCalendarioUsuario(string id_TrabajadorSocial, Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal, Nullable<int> id_Programa)
        {
            var id_TrabajadorSocialParameter = id_TrabajadorSocial != null ?
                new ObjectParameter("Id_TrabajadorSocial", id_TrabajadorSocial) :
                new ObjectParameter("Id_TrabajadorSocial", typeof(string));
    
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("fechaInicial", fechaInicial) :
                new ObjectParameter("fechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            var id_ProgramaParameter = id_Programa.HasValue ?
                new ObjectParameter("Id_Programa", id_Programa) :
                new ObjectParameter("Id_Programa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarCitasCalendarioUsuario_Result>("ListarCitasCalendarioUsuario", id_TrabajadorSocialParameter, fechaInicialParameter, fechaFinalParameter, id_ProgramaParameter);
        }
    
        public virtual int GuardarExcepcionTrabajadorSocial(string id_TrabajadorSocial, Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal)
        {
            var id_TrabajadorSocialParameter = id_TrabajadorSocial != null ?
                new ObjectParameter("Id_TrabajadorSocial", id_TrabajadorSocial) :
                new ObjectParameter("Id_TrabajadorSocial", typeof(string));
    
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("FechaInicial", fechaInicial) :
                new ObjectParameter("FechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarExcepcionTrabajadorSocial", id_TrabajadorSocialParameter, fechaInicialParameter, fechaFinalParameter);
        }
    
        public virtual int EliminarExcepcionesTrabajadorSocial(Nullable<int> id_Excepciones)
        {
            var id_ExcepcionesParameter = id_Excepciones.HasValue ?
                new ObjectParameter("Id_Excepciones", id_Excepciones) :
                new ObjectParameter("Id_Excepciones", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarExcepcionesTrabajadorSocial", id_ExcepcionesParameter);
        }
    }
}
