//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;
namespace Ley22_WebApp_V2.AppCode
{
    //public partial class SEPSEntities : DbContext
    //{
    //    public SEPSEntities()
    //        : base("name=SEPSEntities")
    //    {
    //    }

    //    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    //    {
    //        throw new UnintentionalCodeFirstException();
    //    }


    //    public virtual ObjectResult<SP_READALL_GrupoEtnico_Result> SP_READALL_GrupoEtnico()
    //    {
    //        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_READALL_GrupoEtnico_Result>("SP_READALL_GrupoEtnico");
    //    }

    //    public virtual ObjectResult<SP_READALL_Sexo_Result> SP_READALL_Sexo()
    //    {
    //        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_READALL_Sexo_Result>("SP_READALL_Sexo");
    //    }
    //}
}
