//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace Ley22_WebApp_V2.AppCode
{
    //public partial class Calendario
    //{
    //    public int Id_Calendario { get; set; }
    //    public int Id_TrabajadorSocial { get; set; }
    //    public System.DateTime FechadeSolicitud { get; set; }
    //    public int Id_Participante { get; set; }
    //    public System.DateTime FechaInicial { get; set; }
    //    public System.DateTime FechaFinal { get; set; }
    //    public int Id_OrdenJudicial { get; set; }
    //    public int Asistio { get; set; }
    //}

    //public partial class CCG_Excepciones
    //{
    //    public int PK_CCG_Excepciones { get; set; }
    //    public int Id_Centro { get; set; }
    //    public System.DateTime FechadeSolicitud { get; set; }
    //    public System.DateTime FechaInicial { get; set; }
    //    public System.DateTime FechaFinal { get; set; }
    //}

    //public partial class Centro
    //{
    //    public int Id_Centro { get; set; }
    //    public Nullable<int> Fk_Region { get; set; }
    //    public string NombreDelCentro { get; set; }
    //    public string Direccion { get; set; }
    //    public string Telefono1 { get; set; }
    //    public string Telefono2 { get; set; }
    //}

    //public partial class CharlaGrupal
    //{
    //    public int Id_CharlaGrupal { get; set; }
    //    public int Id_Centro { get; set; }
    //    public System.DateTime FechaInicial { get; set; }
    //    public System.DateTime FechaFinal { get; set; }
    //    public int Id_TipoCharla { get; set; }
    //    public int Id_Nivel { get; set; }
    //    public int NrodeParticipantes { get; set; }
    //    public Nullable<int> Id_Usuario { get; set; }
    //    public Nullable<System.DateTime> FechaCreacion { get; set; }
    //}

    //public partial class Ciudad
    //{
    //    public int Id_Ciudad { get; set; }
    //    public int Id_Region { get; set; }
    //    public string Ciudad1 { get; set; }
    //}

    //public partial class ControldePago
    //{
    //    public int Id_ControldePagos { get; set; }
    //    public int Id_Participante { get; set; }
    //    public int Id_Precio { get; set; }
    //    public int Id_FormadePago { get; set; }
    //    public Nullable<int> NumerodeCheque { get; set; }
    //    public Nullable<System.DateTime> FechadelPago { get; set; }
    //    public Nullable<decimal> Cantidad { get; set; }
    //    public Nullable<int> Estatus { get; set; }
    //    public Nullable<int> Id_Usuario { get; set; }
    //    public Nullable<System.DateTime> FechaRegistro { get; set; }
    //    public Nullable<int> Id_Calendario { get; set; }
    //    public Nullable<int> Id_CharlaGrupal { get; set; }
    //    public Nullable<int> Id_OrdenJudicial { get; set; }
    //}

    //public partial class Documento
    //{
    //    public int Id_Documento { get; set; }
    //    public string Documento1 { get; set; }
    //    public string Archivo { get; set; }
    //    public Nullable<System.DateTime> FechadeRevision { get; set; }
    //    public int Activo { get; set; }
    //}

    //public partial class DocumentosPorParticipante
    //{
    //    public int Id_DocumentoPorParticipante { get; set; }
    //    public int Id_Documento { get; set; }
    //    public int Id_Participante { get; set; }
    //    public int Id_OrdenJudicial { get; set; }
    //    public System.DateTime FechaEntrega { get; set; }
    //    public string PathNameDocumento { get; set; }
    //    public int Id_UsuarioRecibe { get; set; }
    //    public int Aprobado { get; set; }
    //    public Nullable<int> Id_UsuarioAprobacion { get; set; }
    //    public string Comentario { get; set; }
    //}

    //public partial class FormadePago
    //{
    //    public int Id_FormadePago { get; set; }
    //    public string FormadePago1 { get; set; }
    //}

    //public partial class MotivoCierre
    //{
    //    public int Id_MotivoCierre { get; set; }
    //    public string MotivoCierre1 { get; set; }
    //    public int Activo { get; set; }
    //}

    //public partial class NivelesdelasCharla
    //{
    //    public int Id_NiveldeCharla { get; set; }
    //    public string Nivel { get; set; }
    //    public int Activo { get; set; }
    //}

    //public partial class OrdenesJudiciale
    //{
    //    public int Id_OrdenJudicial { get; set; }
    //    public int Id_Participante { get; set; }
    //    public string NumeroOrdenJudicial { get; set; }
    //    public int Activa { get; set; }
    //    public System.DateTime FechaCreacion { get; set; }
    //    public int Id_UsuarioCreacion { get; set; }
    //    public Nullable<System.DateTime> FechaCierre { get; set; }
    //    public Nullable<int> Id_MotivoCierre { get; set; }
    //    public string ComentarioCierre { get; set; }
    //    public string DocumentoAprobacion { get; set; }
    //    public Nullable<int> Id_UsuarioCierre { get; set; }
    //}

    //public partial class Participante
    //{
    //    public int Id_Participante { get; set; }
    //    public string NR_SeguroSocial { get; set; }
    //    public string Identificacion { get; set; }
    //    public string Pasaporte { get; set; }
    //    public string Licencia { get; set; }
    //    public Nullable<int> IUP { get; set; }
    //    public string Expediente { get; set; }
    //    public string NB_Primero { get; set; }
    //    public string NB_Segundo { get; set; }
    //    public string AP_Primero { get; set; }
    //    public string AP_Segundo { get; set; }
    //    public System.DateTime FE_Nacimiento { get; set; }
    //    public byte FK_Sexo { get; set; }
    //    public byte FK_GrupoEtnico { get; set; }
    //    public byte FK_Veterano { get; set; }
    //    public string Correo { get; set; }
    //    public string Telefono1 { get; set; }
    //    public string Telefono2 { get; set; }
    //    public string TelefonoFamiliarMasCercano { get; set; }
    //    public string TelefonoCitas { get; set; }
    //    public string DireccionLinea1 { get; set; }
    //    public string DireccionLinea2 { get; set; }
    //    public string Municipio { get; set; }
    //    public string CodigoPostal { get; set; }
    //    public System.DateTime FE_Edicion { get; set; }
    //    public Nullable<int> Fk_UsuarioEdicion { get; set; }
    //}

    //public partial class ParticipantesPorCharla
    //{
    //    public int Id_ParticipantePorCharlaGrupal { get; set; }
    //    public int Id_CharlaGrupal { get; set; }
    //    public int Id_Participante { get; set; }
    //    public int Id_Usuario { get; set; }
    //    public System.DateTime FechaCreacion { get; set; }
    //    public int Asistio { get; set; }
    //    public Nullable<int> Id_OrdenJudicial { get; set; }
    //}

    //public partial class PERMISO
    //{
    //    public int PK_Permiso { get; set; }
    //    public string NB_Permiso { get; set; }
    //}

    //public partial class Precio
    //{
    //    public int Id_Precio { get; set; }
    //    public string Descripcion { get; set; }
    //    public decimal Cantidad { get; set; }
    //    public System.DateTime Fecha { get; set; }
    //    public int Activo { get; set; }
    //}

    //public partial class Programas_Region_Mapping
    //{
    //    public int FK_Region { get; set; }
    //    public int FK_Programa { get; set; }

    //    public virtual Region Region { get; set; }
    //}

    //public partial class Region
    //{
    //    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    //    public Region()
    //    {
    //        this.Programas_Region_Mapping = new HashSet<Programas_Region_Mapping>();
    //    }

    //    public int Id_Region { get; set; }
    //    public string Region1 { get; set; }

    //    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    //    public virtual ICollection<Programas_Region_Mapping> Programas_Region_Mapping { get; set; }
    //}

    //public partial class SA_PERSONA
    //{
    //    public int PK_Ley22 { get; set; }
    //    public string NR_SeguroSocial { get; set; }
    //    public string Identificacion { get; set; }
    //    public string Pasaporte { get; set; }
    //    public string Licencia { get; set; }
    //    public Nullable<int> IUP { get; set; }
    //    public string Expediente { get; set; }
    //    public string NB_Primero { get; set; }
    //    public string NB_Segundo { get; set; }
    //    public string AP_Primero { get; set; }
    //    public string AP_Segundo { get; set; }
    //    public System.DateTime FE_Nacimiento { get; set; }
    //    public byte FK_Sexo { get; set; }
    //    public byte FK_GrupoEtnico { get; set; }
    //    public byte FK_Veterano { get; set; }
    //    public string Correo { get; set; }
    //    public string Telefono1 { get; set; }
    //    public string Telefono2 { get; set; }
    //    public string TelefonoFamiliarMasCercano { get; set; }
    //    public string TelefonoCitas { get; set; }
    //    public string DireccionLinea1 { get; set; }
    //    public string DireccionLinea2 { get; set; }
    //    public string Municipio { get; set; }
    //    public string CodigoPostal { get; set; }
    //    public System.DateTime FE_Edicion { get; set; }
    //    public Nullable<int> Fk_UsuarioEdicion { get; set; }
    //}

    //public partial class SA_USUARIO_PERMISO_Mapping
    //{
    //    public int FK_Usuario { get; set; }
    //    public int FK_Permiso { get; set; }
    //    public int FK_Programa { get; set; }
    //}

    //public partial class TipodeCharla
    //{
    //    public int Id_TipoCharla { get; set; }
    //    public string TipodeCharla1 { get; set; }
    //    public int Activo { get; set; }
    //}

    //public partial class TrabajadorSocial
    //{
    //    public int Id_TrabajadorSocial { get; set; }
    //    public Nullable<int> Fk_Centro { get; set; }
    //    public string Nombre { get; set; }
    //    public string Telefono1 { get; set; }
    //    public string Telefono2 { get; set; }
    //}

    //public partial class TS_Excepciones
    //{
    //    public int Id_Excepciones { get; set; }
    //    public int Id_TrabajadorSocial { get; set; }
    //    public System.DateTime FechadeSolicitud { get; set; }
    //    public System.DateTime FechaInicial { get; set; }
    //    public System.DateTime FechaFinal { get; set; }
    //}

    //public partial class BuscarSEPSPersonaXNroSeguroSocial_Result
    //{
    //    public int PK_Persona { get; set; }
    //    public string NR_SeguroSocial { get; set; }
    //    public byte FK_Sexo { get; set; }
    //    public string AP_Primero { get; set; }
    //    public string AP_Segundo { get; set; }
    //    public string NB_Primero { get; set; }
    //    public string NB_Segundo { get; set; }
    //    public System.DateTime FE_Nacimiento { get; set; }
    //    public byte FK_Veterano { get; set; }
    //    public byte FK_GrupoEtnico { get; set; }
    //    public System.Guid FK_Sesion { get; set; }
    //    public string TI_Edicion { get; set; }
    //    public System.DateTime FE_Edicion { get; set; }
    //    public string NR_ClientId_Legacy { get; set; }
    //    public Nullable<int> PK_Old { get; set; }
    //}

    //public partial class BusquedaSencilladePersonas_Result
    //{
    //    public int PK_Persona { get; set; }
    //    public int Id_Participante { get; set; }
    //    public string NR_SeguroSocial { get; set; }
    //    public string Identificacion { get; set; }
    //    public Nullable<int> Pasaporte { get; set; }
    //    public Nullable<int> Licencia { get; set; }
    //    public Nullable<int> IUP { get; set; }
    //    public Nullable<int> Expediente { get; set; }
    //    public string NB_Primero { get; set; }
    //    public string NB_Segundo { get; set; }
    //    public string AP_Primero { get; set; }
    //    public string AP_Segundo { get; set; }
    //    public System.DateTime FE_Nacimiento { get; set; }
    //    public byte FK_Sexo { get; set; }
    //    public byte FK_GrupoEtnico { get; set; }
    //    public byte FK_Veterano { get; set; }
    //    public string Correo { get; set; }
    //    public string Telefono1 { get; set; }
    //    public string Telefono2 { get; set; }
    //    public System.DateTime FE_Edicion { get; set; }
    //}

    //public partial class ConsultarCharlasPorParticipante_Result
    //{
    //    public int Id_CharlaGrupal { get; set; }
    //    public string FechaHora { get; set; }
    //    public string NombreDelCentro { get; set; }
    //    public string TipodeCharla { get; set; }
    //    public string Nivel { get; set; }
    //    public int Asistio { get; set; }
    //    public string AsistioTexto { get; set; }
    //}

    //public partial class ConsultarEpisodiosXPersona_Result
    //{
    //    public int PK_Episodio { get; set; }
    //    public System.DateTime FE_Episodio { get; set; }
    //    public string DE_Programa { get; set; }
    //}

    //public partial class DetalleCharlaGrupal_Result
    //{
    //    public int Id_CharlaGrupal { get; set; }
    //    public System.DateTime FechaInicial { get; set; }
    //    public string Horas { get; set; }
    //    public string TipodeCharla { get; set; }
    //    public string Nivel { get; set; }
    //    public string NombreDelCentro { get; set; }
    //}

    //public partial class InfoCharlaGrupal_Result
    //{
    //    public int Id_CharlaGrupal { get; set; }
    //    public System.DateTime FechaInicial { get; set; }
    //    public System.DateTime FechaFinal { get; set; }
    //    public int Id_TipoCharla { get; set; }
    //    public int Id_NiveldeCharla { get; set; }
    //    public int NrodeParticipantes { get; set; }
    //}

    //public partial class ListarBalancedePagos_Result
    //{
    //    public int Id_ControldePagos { get; set; }
    //    public string Descripcion { get; set; }
    //    public string FormadePago { get; set; }
    //    public string NumerodeCheque { get; set; }
    //    public Nullable<System.DateTime> FechadelPago { get; set; }
    //    public Nullable<decimal> Cantidad { get; set; }
    //    public Nullable<int> Estatus { get; set; }
    //    public string NombreCompleto { get; set; }
    //    public decimal CantidadAPagar { get; set; }
    //}

    //public partial class ListarCharlasCalendario_Result
    //{
    //    public int Id_CharlaGrupal { get; set; }
    //    public int NrodeParticipantes { get; set; }
    //    public System.DateTime FechaInicial { get; set; }
    //    public System.DateTime FechaFinal { get; set; }
    //    public string TipodeCharla { get; set; }
    //    public string Nivel { get; set; }
    //}

    //public partial class ListarCitasCalendario_Result
    //{
    //    public int Id_Calendario { get; set; }
    //    public System.DateTime FechaInicial { get; set; }
    //    public System.DateTime FechaFinal { get; set; }
    //    public string NB_Primero { get; set; }
    //    public string AP_Primero { get; set; }
    //    public System.DateTime FE_Nacimiento { get; set; }
    //    public string NR_SeguroSocial { get; set; }
    //    public string TelefonoCitas { get; set; }
    //}

    //public partial class ListarDocumentosActivos_Result
    //{
    //    public int Id_Documento { get; set; }
    //    public string Documento { get; set; }
    //    public string Archivo { get; set; }
    //    public int Activo { get; set; }
    //    public Nullable<System.DateTime> FechadeRevision { get; set; }
    //}

    //public partial class ListarDocumentosRecibidos_Result
    //{
    //    public int Id_DocumentoPorParticipante { get; set; }
    //    public string Documento { get; set; }
    //    public string NumeroOrdenJudicial { get; set; }
    //    public string PathNameDocumento { get; set; }
    //    public System.DateTime FechaEntrega { get; set; }
    //    public int Aprobado { get; set; }
    //    public string AprobadoTexto { get; set; }
    //    public int Id_OrdenJudicial { get; set; }
    //}

    //public partial class ListarExcepcionesCharlaGrupal_Result
    //{
    //    public int PK_CCG_Excepciones { get; set; }
    //    public System.DateTime FechaInicial { get; set; }
    //    public System.DateTime FechaFinal { get; set; }
    //}

    //public partial class ListarExcepcionesTrabajadorSocial_Result
    //{
    //    public int Id_Excepciones { get; set; }
    //    public System.DateTime FechaInicial { get; set; }
    //    public System.DateTime FechaFinal { get; set; }
    //}

    //public partial class ListarMotivosCierre_Result
    //{
    //    public int Id_MotivoCierre { get; set; }
    //    public string MotivoCierre { get; set; }
    //    public int Activo { get; set; }
    //}

    //public partial class ListarOrdenesJudicialesActivas_Result
    //{
    //    public int Id_OrdenJudicial { get; set; }
    //    public int Id_Participante { get; set; }
    //    public string NumeroOrdenJudicial { get; set; }
    //    public int Activa { get; set; }
    //    public System.DateTime FechaCreacion { get; set; }
    //    public int Id_UsuarioCreacion { get; set; }
    //    public Nullable<System.DateTime> FechaCierre { get; set; }
    //    public Nullable<int> Id_MotivoCierre { get; set; }
    //    public string ComentarioCierre { get; set; }
    //    public string DocumentoAprobacion { get; set; }
    //    public Nullable<int> Id_UsuarioCierre { get; set; }
    //}

    //public partial class ListarParticipantesPorCharlas_Result
    //{
    //    public int Id_ParticipantePorCharlaGrupal { get; set; }
    //    public int Id_CharlaGrupal { get; set; }
    //    public int Id_Participante { get; set; }
    //    public string NB_Primero { get; set; }
    //    public string AP_Primero { get; set; }
    //}

    //public partial class ListarTipodeDocumentosPorParticipanteOrdenJudicial_Result
    //{
    //    public int Id_Documento { get; set; }
    //    public string Documento { get; set; }
    //    public string Archivo { get; set; }
    //    public Nullable<System.DateTime> FechadeRevision { get; set; }
    //    public int Activo { get; set; }
    //}

    //public partial class ResumendeAsistenciasCharlas_Result
    //{
    //    public Nullable<int> TotaldeCharlas { get; set; }
    //    public Nullable<int> TotalAsistencias { get; set; }
    //    public Nullable<int> TotalInasistencias { get; set; }
    //}

    //public partial class Sp_Read_CalendariobyId_Result
    //{
    //    public int Id_Calendario { get; set; }
    //    public string FechaHora { get; set; }
    //    public string TrabajadorSocial { get; set; }
    //    public string NombreDelCentro { get; set; }
    //    public int Asistio { get; set; }
    //    public string AsistioTexto { get; set; }
    //}

    //public partial class sp_READ_CentrobyRegion_Result
    //{
    //    public short PK_Programa { get; set; }
    //    public string NB_Programa { get; set; }
    //    public string DE_Programa { get; set; }
    //    public string NB_ProgramaIngles { get; set; }
    //}

    //public partial class sp_READ_ParticipantesxId_Result
    //{
    //    public int Id_Participante { get; set; }
    //    public string NR_SeguroSocial { get; set; }
    //    public string Identificacion { get; set; }
    //    public string Pasaporte { get; set; }
    //    public string Licencia { get; set; }
    //    public int IUP { get; set; }
    //    public string Expediente { get; set; }
    //    public string NB_Primero { get; set; }
    //    public string NB_Segundo { get; set; }
    //    public string AP_Primero { get; set; }
    //    public string AP_Segundo { get; set; }
    //    public System.DateTime FE_Nacimiento { get; set; }
    //    public byte FK_Sexo { get; set; }
    //    public byte FK_GrupoEtnico { get; set; }
    //    public byte FK_Veterano { get; set; }
    //    public string Correo { get; set; }
    //    public string Telefono1 { get; set; }
    //    public string Telefono2 { get; set; }
    //    public string TelefonoFamiliarMasCercano { get; set; }
    //    public string TelefonoCitas { get; set; }
    //    public string DireccionLinea1 { get; set; }
    //    public string DireccionLinea2 { get; set; }
    //    public string Municipio { get; set; }
    //    public string CodigoPostal { get; set; }
    //    public System.DateTime FE_Edicion { get; set; }
    //    public int Fk_UsuarioEdicion { get; set; }
    //    public string DE_Sexo { get; set; }
    //    public string DE_GrupoEtnico { get; set; }
    //}

    //public partial class sp_READ_SA_PERSONAxId_Result
    //{
    //    public int Pk_Persona { get; set; }
    //    public int Id_Participante { get; set; }
    //    public string NR_SeguroSocial { get; set; }
    //    public string Identificacion { get; set; }
    //    public string Pasaporte { get; set; }
    //    public string Licencia { get; set; }
    //    public int IUP { get; set; }
    //    public string Expediente { get; set; }
    //    public string NB_Primero { get; set; }
    //    public string NB_Segundo { get; set; }
    //    public string AP_Primero { get; set; }
    //    public string AP_Segundo { get; set; }
    //    public System.DateTime FE_Nacimiento { get; set; }
    //    public byte FK_Sexo { get; set; }
    //    public byte FK_GrupoEtnico { get; set; }
    //    public byte FK_Veterano { get; set; }
    //    public string Correo { get; set; }
    //    public string Telefono1 { get; set; }
    //    public string Telefono2 { get; set; }
    //    public string TelefonoFamiliarMasCercano { get; set; }
    //    public string TelefonoCitas { get; set; }
    //    public string DireccionLinea1 { get; set; }
    //    public string DireccionLinea2 { get; set; }
    //    public string Municipio { get; set; }
    //    public string CodigoPostal { get; set; }
    //    public System.DateTime FE_Edicion { get; set; }
    //    public int Fk_UsuarioEdicion { get; set; }
    //    public string DE_Sexo { get; set; }
    //    public string DE_GrupoEtnico { get; set; }
    //}

    //public partial class sp_READ_TrabajadorSocialbyCentro_Result
    //{
    //    public int PK_USUARIO { get; set; }
    //    public string NB_USUARIO { get; set; }
    //}

    //public partial class sp_READALL_Ciudad_Result
    //{
    //    public int Id_Ciudad { get; set; }
    //    public string Ciudad { get; set; }
    //}

    //public partial class sp_READALL_NivelesdelasCharlas_Result
    //{
    //    public int Id_NiveldeCharla { get; set; }
    //    public string Nivel { get; set; }
    //    public int Activo { get; set; }
    //}

    //public partial class sp_READALL_Regiones_Result
    //{
    //    public int Id_region { get; set; }
    //    public string region { get; set; }
    //}

    //public partial class sp_READALL_TipodeCharlas_Result
    //{
    //    public int Id_TipoCharla { get; set; }
    //    public string TipodeCharla { get; set; }
    //    public int Activo { get; set; }
    //}
}