//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Ley22_WebApp_V2.AppCode
{
    //using System;
    //using System.Collections.Generic;

    //public partial class SP_READALL_GrupoEtnico_Result
    //{
    //    public byte PK_GrupoEtnico { get; set; }
    //    public string CO_TEDS { get; set; }
    //    public string DE_GrupoEtnico { get; set; }
    //    public string CO_TEDS_MH { get; set; }
    //    public Nullable<bool> Active { get; set; }
    //    public Nullable<int> Ordered { get; set; }
    //}

    //public partial class SP_READALL_Sexo_Result
    //{
    //    public byte PK_Sexo { get; set; }
    //    public string CO_TEDS { get; set; }
    //    public string CO_TEDS_MH { get; set; }
    //    public string DE_Sexo { get; set; }
    //    public Nullable<int> Ordered { get; set; }
    //    public Nullable<bool> Active { get; set; }
    //}
}
