//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ley22_WebApp_V2.Old_App_Code
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Ley22Entities : DbContext
    {
        public Ley22Entities()
            : base("name=Ley22Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Centro> Centros { get; set; }
        public virtual DbSet<Ciudad> Ciudads { get; set; }
        public virtual DbSet<FormadePago> FormadePagoes { get; set; }
        public virtual DbSet<MotivoCierre> MotivoCierres { get; set; }
        public virtual DbSet<NivelesdelasCharla> NivelesdelasCharlas { get; set; }
        public virtual DbSet<Participante> Participantes { get; set; }
        public virtual DbSet<Precio> Precios { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<TipodeCharla> TipodeCharlas { get; set; }
        public virtual DbSet<TrabajadorSocial> TrabajadorSocials { get; set; }
        public virtual DbSet<Programas_Region_Mapping> Programas_Region_Mapping { get; set; }
        public virtual DbSet<CCG_Excepciones> CCG_Excepciones { get; set; }
        public virtual DbSet<PERMISO> PERMISOes { get; set; }
        public virtual DbSet<SA_USUARIO_PERMISO_Mapping> SA_USUARIO_PERMISO_Mapping { get; set; }
        public virtual DbSet<USUARIO_PROGRAMA> USUARIO_PROGRAMA { get; set; }
        public virtual DbSet<Calendario> Calendarios { get; set; }
        public virtual DbSet<ParticipantesPorCharla> ParticipantesPorCharlas { get; set; }
        public virtual DbSet<CharlaGrupal> CharlaGrupals { get; set; }
        public virtual DbSet<OrdenesJudiciale> OrdenesJudiciales { get; set; }
        public virtual DbSet<DocumentosPorParticipante> DocumentosPorParticipantes { get; set; }
        public virtual DbSet<Tribunal> Tribunals { get; set; }
        public virtual DbSet<DesempleoRazon> DesempleoRazons { get; set; }
        public virtual DbSet<TS_Excepciones> TS_Excepciones { get; set; }
        public virtual DbSet<Documento> Documentos { get; set; }
        public virtual DbSet<CasoCriminal> CasoCriminals { get; set; }
        public virtual DbSet<ControldePago> ControldePagoes { get; set; }
    
        public virtual ObjectResult<BuscarSEPSPersonaXNroSeguroSocial_Result> BuscarSEPSPersonaXNroSeguroSocial(string nR_SeguroSocial)
        {
            var nR_SeguroSocialParameter = nR_SeguroSocial != null ?
                new ObjectParameter("NR_SeguroSocial", nR_SeguroSocial) :
                new ObjectParameter("NR_SeguroSocial", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BuscarSEPSPersonaXNroSeguroSocial_Result>("BuscarSEPSPersonaXNroSeguroSocial", nR_SeguroSocialParameter);
        }
    
        public virtual int CerrarordenJudicial(Nullable<int> id_OrdenJudicial, Nullable<int> id_MotivoCierre, string comentarioCierre, string documentoAprobacion, Nullable<int> id_UsuarioCierre)
        {
            var id_OrdenJudicialParameter = id_OrdenJudicial.HasValue ?
                new ObjectParameter("Id_OrdenJudicial", id_OrdenJudicial) :
                new ObjectParameter("Id_OrdenJudicial", typeof(int));
    
            var id_MotivoCierreParameter = id_MotivoCierre.HasValue ?
                new ObjectParameter("Id_MotivoCierre", id_MotivoCierre) :
                new ObjectParameter("Id_MotivoCierre", typeof(int));
    
            var comentarioCierreParameter = comentarioCierre != null ?
                new ObjectParameter("ComentarioCierre", comentarioCierre) :
                new ObjectParameter("ComentarioCierre", typeof(string));
    
            var documentoAprobacionParameter = documentoAprobacion != null ?
                new ObjectParameter("DocumentoAprobacion", documentoAprobacion) :
                new ObjectParameter("DocumentoAprobacion", typeof(string));
    
            var id_UsuarioCierreParameter = id_UsuarioCierre.HasValue ?
                new ObjectParameter("Id_UsuarioCierre", id_UsuarioCierre) :
                new ObjectParameter("Id_UsuarioCierre", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CerrarordenJudicial", id_OrdenJudicialParameter, id_MotivoCierreParameter, comentarioCierreParameter, documentoAprobacionParameter, id_UsuarioCierreParameter);
        }
    
        public virtual ObjectResult<ConsultarEpisodiosXPersona_Result> ConsultarEpisodiosXPersona(Nullable<int> pk_Persona)
        {
            var pk_PersonaParameter = pk_Persona.HasValue ?
                new ObjectParameter("Pk_Persona", pk_Persona) :
                new ObjectParameter("Pk_Persona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarEpisodiosXPersona_Result>("ConsultarEpisodiosXPersona", pk_PersonaParameter);
        }
    
        public virtual int EliminarCharlaGrupal(Nullable<int> id_CharlaGrupal)
        {
            var id_CharlaGrupalParameter = id_CharlaGrupal.HasValue ?
                new ObjectParameter("Id_CharlaGrupal", id_CharlaGrupal) :
                new ObjectParameter("Id_CharlaGrupal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarCharlaGrupal", id_CharlaGrupalParameter);
        }
    
        public virtual int EliminarCitaTrabajadorSocial(Nullable<int> id_Calendario)
        {
            var id_CalendarioParameter = id_Calendario.HasValue ?
                new ObjectParameter("Id_Calendario", id_Calendario) :
                new ObjectParameter("Id_Calendario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarCitaTrabajadorSocial", id_CalendarioParameter);
        }
    
        public virtual int EliminarDocuemntoPorParticipante(Nullable<int> id_DocumentoPorParticipante)
        {
            var id_DocumentoPorParticipanteParameter = id_DocumentoPorParticipante.HasValue ?
                new ObjectParameter("Id_DocumentoPorParticipante", id_DocumentoPorParticipante) :
                new ObjectParameter("Id_DocumentoPorParticipante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarDocuemntoPorParticipante", id_DocumentoPorParticipanteParameter);
        }
    
        public virtual int EliminarParticipanteCharlaGrupal(Nullable<int> id_CharlaGrupal, Nullable<int> id_Participante)
        {
            var id_CharlaGrupalParameter = id_CharlaGrupal.HasValue ?
                new ObjectParameter("Id_CharlaGrupal", id_CharlaGrupal) :
                new ObjectParameter("Id_CharlaGrupal", typeof(int));
    
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarParticipanteCharlaGrupal", id_CharlaGrupalParameter, id_ParticipanteParameter);
        }
    
        public virtual ObjectResult<ListarDocumentosActivos_Result> ListarDocumentosActivos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarDocumentosActivos_Result>("ListarDocumentosActivos");
        }
    
        public virtual ObjectResult<ListarMotivosCierre_Result> ListarMotivosCierre()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarMotivosCierre_Result>("ListarMotivosCierre");
        }
    
        public virtual ObjectResult<ResumendeAsistenciasCharlas_Result> ResumendeAsistenciasCharlas(Nullable<int> id_Participante)
        {
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ResumendeAsistenciasCharlas_Result>("ResumendeAsistenciasCharlas", id_ParticipanteParameter);
        }
    
        public virtual ObjectResult<Sp_Read_CalendariobyId_Result> Sp_Read_CalendariobyId(Nullable<int> id_Participante)
        {
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Read_CalendariobyId_Result>("Sp_Read_CalendariobyId", id_ParticipanteParameter);
        }
    
        public virtual ObjectResult<sp_READ_CentrobyRegion_Result> sp_READ_CentrobyRegion(Nullable<int> id_Region)
        {
            var id_RegionParameter = id_Region.HasValue ?
                new ObjectParameter("Id_Region", id_Region) :
                new ObjectParameter("Id_Region", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_READ_CentrobyRegion_Result>("sp_READ_CentrobyRegion", id_RegionParameter);
        }
    
        public virtual ObjectResult<sp_READ_ParticipantesxId_Result> sp_READ_ParticipantesxId(Nullable<int> id_Participante)
        {
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_READ_ParticipantesxId_Result>("sp_READ_ParticipantesxId", id_ParticipanteParameter);
        }
    
        public virtual ObjectResult<sp_READ_SA_PERSONAxId_Result> sp_READ_SA_PERSONAxId(Nullable<int> id_Participante, Nullable<int> pk_Persona)
        {
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            var pk_PersonaParameter = pk_Persona.HasValue ?
                new ObjectParameter("Pk_Persona", pk_Persona) :
                new ObjectParameter("Pk_Persona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_READ_SA_PERSONAxId_Result>("sp_READ_SA_PERSONAxId", id_ParticipanteParameter, pk_PersonaParameter);
        }
    
        public virtual ObjectResult<sp_READ_TrabajadorSocialbyCentro_Result> sp_READ_TrabajadorSocialbyCentro(Nullable<int> id_Centro)
        {
            var id_CentroParameter = id_Centro.HasValue ?
                new ObjectParameter("Id_Centro", id_Centro) :
                new ObjectParameter("Id_Centro", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_READ_TrabajadorSocialbyCentro_Result>("sp_READ_TrabajadorSocialbyCentro", id_CentroParameter);
        }
    
        public virtual ObjectResult<sp_READALL_Ciudad_Result> sp_READALL_Ciudad(Nullable<int> id_Region)
        {
            var id_RegionParameter = id_Region.HasValue ?
                new ObjectParameter("Id_Region", id_Region) :
                new ObjectParameter("Id_Region", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_READALL_Ciudad_Result>("sp_READALL_Ciudad", id_RegionParameter);
        }
    
        public virtual ObjectResult<sp_READALL_NivelesdelasCharlas_Result> sp_READALL_NivelesdelasCharlas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_READALL_NivelesdelasCharlas_Result>("sp_READALL_NivelesdelasCharlas");
        }
    
        public virtual ObjectResult<sp_READALL_Regiones_Result> sp_READALL_Regiones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_READALL_Regiones_Result>("sp_READALL_Regiones");
        }
    
        public virtual ObjectResult<sp_READALL_TipodeCharlas_Result> sp_READALL_TipodeCharlas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_READALL_TipodeCharlas_Result>("sp_READALL_TipodeCharlas");
        }
    
        public virtual ObjectResult<Nullable<int>> SPC_Persona(string nR_SeguroSocial, string identificacion, string pasaporte, string licencia, Nullable<int> iUP, string expediente, string nB_Primero, string nB_Segundo, string aP_Primero, string aP_Segundo, Nullable<System.DateTime> fE_Nacimiento, Nullable<byte> fK_Sexo, Nullable<byte> fK_GrupoEtnico, Nullable<byte> fK_Veterano, string correo, string telefono1, string telefono2, string telefonoFamiliarMasCercano, string telefonoCitas, string direccionLinea1, string direccionLinea2, string municipio, string codigoPostal, Nullable<int> fk_UsuarioEdicion, Nullable<int> id_Participante)
        {
            var nR_SeguroSocialParameter = nR_SeguroSocial != null ?
                new ObjectParameter("NR_SeguroSocial", nR_SeguroSocial) :
                new ObjectParameter("NR_SeguroSocial", typeof(string));
    
            var identificacionParameter = identificacion != null ?
                new ObjectParameter("Identificacion", identificacion) :
                new ObjectParameter("Identificacion", typeof(string));
    
            var pasaporteParameter = pasaporte != null ?
                new ObjectParameter("Pasaporte", pasaporte) :
                new ObjectParameter("Pasaporte", typeof(string));
    
            var licenciaParameter = licencia != null ?
                new ObjectParameter("Licencia", licencia) :
                new ObjectParameter("Licencia", typeof(string));
    
            var iUPParameter = iUP.HasValue ?
                new ObjectParameter("IUP", iUP) :
                new ObjectParameter("IUP", typeof(int));
    
            var expedienteParameter = expediente != null ?
                new ObjectParameter("Expediente", expediente) :
                new ObjectParameter("Expediente", typeof(string));
    
            var nB_PrimeroParameter = nB_Primero != null ?
                new ObjectParameter("NB_Primero", nB_Primero) :
                new ObjectParameter("NB_Primero", typeof(string));
    
            var nB_SegundoParameter = nB_Segundo != null ?
                new ObjectParameter("NB_Segundo", nB_Segundo) :
                new ObjectParameter("NB_Segundo", typeof(string));
    
            var aP_PrimeroParameter = aP_Primero != null ?
                new ObjectParameter("AP_Primero", aP_Primero) :
                new ObjectParameter("AP_Primero", typeof(string));
    
            var aP_SegundoParameter = aP_Segundo != null ?
                new ObjectParameter("AP_Segundo", aP_Segundo) :
                new ObjectParameter("AP_Segundo", typeof(string));
    
            var fE_NacimientoParameter = fE_Nacimiento.HasValue ?
                new ObjectParameter("FE_Nacimiento", fE_Nacimiento) :
                new ObjectParameter("FE_Nacimiento", typeof(System.DateTime));
    
            var fK_SexoParameter = fK_Sexo.HasValue ?
                new ObjectParameter("FK_Sexo", fK_Sexo) :
                new ObjectParameter("FK_Sexo", typeof(byte));
    
            var fK_GrupoEtnicoParameter = fK_GrupoEtnico.HasValue ?
                new ObjectParameter("FK_GrupoEtnico", fK_GrupoEtnico) :
                new ObjectParameter("FK_GrupoEtnico", typeof(byte));
    
            var fK_VeteranoParameter = fK_Veterano.HasValue ?
                new ObjectParameter("FK_Veterano", fK_Veterano) :
                new ObjectParameter("FK_Veterano", typeof(byte));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var telefono1Parameter = telefono1 != null ?
                new ObjectParameter("Telefono1", telefono1) :
                new ObjectParameter("Telefono1", typeof(string));
    
            var telefono2Parameter = telefono2 != null ?
                new ObjectParameter("Telefono2", telefono2) :
                new ObjectParameter("Telefono2", typeof(string));
    
            var telefonoFamiliarMasCercanoParameter = telefonoFamiliarMasCercano != null ?
                new ObjectParameter("TelefonoFamiliarMasCercano", telefonoFamiliarMasCercano) :
                new ObjectParameter("TelefonoFamiliarMasCercano", typeof(string));
    
            var telefonoCitasParameter = telefonoCitas != null ?
                new ObjectParameter("TelefonoCitas", telefonoCitas) :
                new ObjectParameter("TelefonoCitas", typeof(string));
    
            var direccionLinea1Parameter = direccionLinea1 != null ?
                new ObjectParameter("DireccionLinea1", direccionLinea1) :
                new ObjectParameter("DireccionLinea1", typeof(string));
    
            var direccionLinea2Parameter = direccionLinea2 != null ?
                new ObjectParameter("DireccionLinea2", direccionLinea2) :
                new ObjectParameter("DireccionLinea2", typeof(string));
    
            var municipioParameter = municipio != null ?
                new ObjectParameter("Municipio", municipio) :
                new ObjectParameter("Municipio", typeof(string));
    
            var codigoPostalParameter = codigoPostal != null ?
                new ObjectParameter("CodigoPostal", codigoPostal) :
                new ObjectParameter("CodigoPostal", typeof(string));
    
            var fk_UsuarioEdicionParameter = fk_UsuarioEdicion.HasValue ?
                new ObjectParameter("Fk_UsuarioEdicion", fk_UsuarioEdicion) :
                new ObjectParameter("Fk_UsuarioEdicion", typeof(int));
    
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SPC_Persona", nR_SeguroSocialParameter, identificacionParameter, pasaporteParameter, licenciaParameter, iUPParameter, expedienteParameter, nB_PrimeroParameter, nB_SegundoParameter, aP_PrimeroParameter, aP_SegundoParameter, fE_NacimientoParameter, fK_SexoParameter, fK_GrupoEtnicoParameter, fK_VeteranoParameter, correoParameter, telefono1Parameter, telefono2Parameter, telefonoFamiliarMasCercanoParameter, telefonoCitasParameter, direccionLinea1Parameter, direccionLinea2Parameter, municipioParameter, codigoPostalParameter, fk_UsuarioEdicionParameter, id_ParticipanteParameter);
        }
    
        public virtual int AsignaCitaTrabajadorSocial(Nullable<int> id_TrabajadorSocial, Nullable<int> pK_Ley22, Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal, Nullable<int> id_OrdenJudicial)
        {
            var id_TrabajadorSocialParameter = id_TrabajadorSocial.HasValue ?
                new ObjectParameter("Id_TrabajadorSocial", id_TrabajadorSocial) :
                new ObjectParameter("Id_TrabajadorSocial", typeof(int));
    
            var pK_Ley22Parameter = pK_Ley22.HasValue ?
                new ObjectParameter("PK_Ley22", pK_Ley22) :
                new ObjectParameter("PK_Ley22", typeof(int));
    
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("FechaInicial", fechaInicial) :
                new ObjectParameter("FechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            var id_OrdenJudicialParameter = id_OrdenJudicial.HasValue ?
                new ObjectParameter("Id_OrdenJudicial", id_OrdenJudicial) :
                new ObjectParameter("Id_OrdenJudicial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AsignaCitaTrabajadorSocial", id_TrabajadorSocialParameter, pK_Ley22Parameter, fechaInicialParameter, fechaFinalParameter, id_OrdenJudicialParameter);
        }
    
        public virtual int ListarCalendario(Nullable<int> id_TrabajadorSocial)
        {
            var id_TrabajadorSocialParameter = id_TrabajadorSocial.HasValue ?
                new ObjectParameter("Id_TrabajadorSocial", id_TrabajadorSocial) :
                new ObjectParameter("Id_TrabajadorSocial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListarCalendario", id_TrabajadorSocialParameter);
        }
    
        public virtual int GuardarExcepcionCoordinadorCharlasGrupales(Nullable<int> id_Centro, Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal)
        {
            var id_CentroParameter = id_Centro.HasValue ?
                new ObjectParameter("Id_Centro", id_Centro) :
                new ObjectParameter("Id_Centro", typeof(int));
    
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("FechaInicial", fechaInicial) :
                new ObjectParameter("FechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarExcepcionCoordinadorCharlasGrupales", id_CentroParameter, fechaInicialParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<ListarExcepcionesCharlaGrupal_Result> ListarExcepcionesCharlaGrupal(Nullable<int> id_Centro, Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal)
        {
            var id_CentroParameter = id_Centro.HasValue ?
                new ObjectParameter("Id_Centro", id_Centro) :
                new ObjectParameter("Id_Centro", typeof(int));
    
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("fechaInicial", fechaInicial) :
                new ObjectParameter("fechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarExcepcionesCharlaGrupal_Result>("ListarExcepcionesCharlaGrupal", id_CentroParameter, fechaInicialParameter, fechaFinalParameter);
        }
    
        public virtual int EliminarExcepcionesTrabajadorSocial(Nullable<int> id_Excepciones)
        {
            var id_ExcepcionesParameter = id_Excepciones.HasValue ?
                new ObjectParameter("Id_Excepciones", id_Excepciones) :
                new ObjectParameter("Id_Excepciones", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarExcepcionesTrabajadorSocial", id_ExcepcionesParameter);
        }
    
        public virtual int AsistioCitaTrabajadorSocial(Nullable<int> id_Calendario)
        {
            var id_CalendarioParameter = id_Calendario.HasValue ?
                new ObjectParameter("Id_Calendario", id_Calendario) :
                new ObjectParameter("Id_Calendario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AsistioCitaTrabajadorSocial", id_CalendarioParameter);
        }
    
        public virtual int NoAsistioCitaTrabajadorSocial(Nullable<int> id_Calendario)
        {
            var id_CalendarioParameter = id_Calendario.HasValue ?
                new ObjectParameter("Id_Calendario", id_Calendario) :
                new ObjectParameter("Id_Calendario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NoAsistioCitaTrabajadorSocial", id_CalendarioParameter);
        }
    
        public virtual int GuardarObservaciones(Nullable<int> id_Calendario, string texto)
        {
            var id_CalendarioParameter = id_Calendario.HasValue ?
                new ObjectParameter("Id_Calendario", id_Calendario) :
                new ObjectParameter("Id_Calendario", typeof(int));
    
            var textoParameter = texto != null ?
                new ObjectParameter("Texto", texto) :
                new ObjectParameter("Texto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarObservaciones", id_CalendarioParameter, textoParameter);
        }
    
        public virtual ObjectResult<ListarCitasCalendario_Result> ListarCitasCalendario(string id_TrabajadorSocial, Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal)
        {
            var id_TrabajadorSocialParameter = id_TrabajadorSocial != null ?
                new ObjectParameter("Id_TrabajadorSocial", id_TrabajadorSocial) :
                new ObjectParameter("Id_TrabajadorSocial", typeof(string));
    
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("fechaInicial", fechaInicial) :
                new ObjectParameter("fechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarCitasCalendario_Result>("ListarCitasCalendario", id_TrabajadorSocialParameter, fechaInicialParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<ListarCitasCalendarioUsuario_Result> ListarCitasCalendarioUsuario(string id_TrabajadorSocial, Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal, Nullable<int> id_Programa)
        {
            var id_TrabajadorSocialParameter = id_TrabajadorSocial != null ?
                new ObjectParameter("Id_TrabajadorSocial", id_TrabajadorSocial) :
                new ObjectParameter("Id_TrabajadorSocial", typeof(string));
    
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("fechaInicial", fechaInicial) :
                new ObjectParameter("fechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            var id_ProgramaParameter = id_Programa.HasValue ?
                new ObjectParameter("Id_Programa", id_Programa) :
                new ObjectParameter("Id_Programa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarCitasCalendarioUsuario_Result>("ListarCitasCalendarioUsuario", id_TrabajadorSocialParameter, fechaInicialParameter, fechaFinalParameter, id_ProgramaParameter);
        }
    
        public virtual ObjectResult<DetalleCharlaGrupal_Result> DetalleCharlaGrupal(Nullable<int> id_CharlaGrupal)
        {
            var id_CharlaGrupalParameter = id_CharlaGrupal.HasValue ?
                new ObjectParameter("Id_CharlaGrupal", id_CharlaGrupal) :
                new ObjectParameter("Id_CharlaGrupal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DetalleCharlaGrupal_Result>("DetalleCharlaGrupal", id_CharlaGrupalParameter);
        }
    
        public virtual ObjectResult<InfoCharlaGrupal_Result> InfoCharlaGrupal(Nullable<int> id_CharlaGrupal)
        {
            var id_CharlaGrupalParameter = id_CharlaGrupal.HasValue ?
                new ObjectParameter("Id_CharlaGrupal", id_CharlaGrupal) :
                new ObjectParameter("Id_CharlaGrupal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InfoCharlaGrupal_Result>("InfoCharlaGrupal", id_CharlaGrupalParameter);
        }
    
        public virtual ObjectResult<ListarCharlasCalendario_Result> ListarCharlasCalendario(Nullable<int> id_Centro, Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal)
        {
            var id_CentroParameter = id_Centro.HasValue ?
                new ObjectParameter("Id_Centro", id_Centro) :
                new ObjectParameter("Id_Centro", typeof(int));
    
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("fechaInicial", fechaInicial) :
                new ObjectParameter("fechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarCharlasCalendario_Result>("ListarCharlasCalendario", id_CentroParameter, fechaInicialParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<ListarCitasCalendarioAdministrador_Result> ListarCitasCalendarioAdministrador(Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal, Nullable<int> id_Programa)
        {
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("fechaInicial", fechaInicial) :
                new ObjectParameter("fechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            var id_ProgramaParameter = id_Programa.HasValue ?
                new ObjectParameter("Id_Programa", id_Programa) :
                new ObjectParameter("Id_Programa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarCitasCalendarioAdministrador_Result>("ListarCitasCalendarioAdministrador", fechaInicialParameter, fechaFinalParameter, id_ProgramaParameter);
        }
    
        public virtual int AsistioCharla(Nullable<int> id_ParticipantePorCharlaGrupal)
        {
            var id_ParticipantePorCharlaGrupalParameter = id_ParticipantePorCharlaGrupal.HasValue ?
                new ObjectParameter("Id_ParticipantePorCharlaGrupal", id_ParticipantePorCharlaGrupal) :
                new ObjectParameter("Id_ParticipantePorCharlaGrupal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AsistioCharla", id_ParticipantePorCharlaGrupalParameter);
        }
    
        public virtual int NoAsistioCharla(Nullable<int> id_ParticipantePorCharlaGrupal)
        {
            var id_ParticipantePorCharlaGrupalParameter = id_ParticipantePorCharlaGrupal.HasValue ?
                new ObjectParameter("Id_ParticipantePorCharlaGrupal", id_ParticipantePorCharlaGrupal) :
                new ObjectParameter("Id_ParticipantePorCharlaGrupal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NoAsistioCharla", id_ParticipantePorCharlaGrupalParameter);
        }
    
        public virtual ObjectResult<ListarParticipantesPorCharlas_Result> ListarParticipantesPorCharlas(Nullable<int> id_CharlaGrupal)
        {
            var id_CharlaGrupalParameter = id_CharlaGrupal.HasValue ?
                new ObjectParameter("Id_CharlaGrupal", id_CharlaGrupal) :
                new ObjectParameter("Id_CharlaGrupal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarParticipantesPorCharlas_Result>("ListarParticipantesPorCharlas", id_CharlaGrupalParameter);
        }
    
        public virtual int GuardarParticipantePorCharlas(Nullable<int> id_CharlaGrupal, Nullable<int> id_Participante, string id_Usuario, Nullable<int> id_OrdenJudicial, Nullable<int> numeroCharla)
        {
            var id_CharlaGrupalParameter = id_CharlaGrupal.HasValue ?
                new ObjectParameter("Id_CharlaGrupal", id_CharlaGrupal) :
                new ObjectParameter("Id_CharlaGrupal", typeof(int));
    
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            var id_UsuarioParameter = id_Usuario != null ?
                new ObjectParameter("Id_Usuario", id_Usuario) :
                new ObjectParameter("Id_Usuario", typeof(string));
    
            var id_OrdenJudicialParameter = id_OrdenJudicial.HasValue ?
                new ObjectParameter("Id_OrdenJudicial", id_OrdenJudicial) :
                new ObjectParameter("Id_OrdenJudicial", typeof(int));
    
            var numeroCharlaParameter = numeroCharla.HasValue ?
                new ObjectParameter("NumeroCharla", numeroCharla) :
                new ObjectParameter("NumeroCharla", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarParticipantePorCharlas", id_CharlaGrupalParameter, id_ParticipanteParameter, id_UsuarioParameter, id_OrdenJudicialParameter, numeroCharlaParameter);
        }
    
        public virtual int GuardarCharlaGrupal(Nullable<int> id_Centro, Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal, Nullable<int> id_TipoCharla, Nullable<int> id_Nivel, Nullable<int> nrodeParticipantes, string id_Usuario, Nullable<int> numeroCharla)
        {
            var id_CentroParameter = id_Centro.HasValue ?
                new ObjectParameter("Id_Centro", id_Centro) :
                new ObjectParameter("Id_Centro", typeof(int));
    
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("FechaInicial", fechaInicial) :
                new ObjectParameter("FechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            var id_TipoCharlaParameter = id_TipoCharla.HasValue ?
                new ObjectParameter("Id_TipoCharla", id_TipoCharla) :
                new ObjectParameter("Id_TipoCharla", typeof(int));
    
            var id_NivelParameter = id_Nivel.HasValue ?
                new ObjectParameter("Id_Nivel", id_Nivel) :
                new ObjectParameter("Id_Nivel", typeof(int));
    
            var nrodeParticipantesParameter = nrodeParticipantes.HasValue ?
                new ObjectParameter("NrodeParticipantes", nrodeParticipantes) :
                new ObjectParameter("NrodeParticipantes", typeof(int));
    
            var id_UsuarioParameter = id_Usuario != null ?
                new ObjectParameter("Id_Usuario", id_Usuario) :
                new ObjectParameter("Id_Usuario", typeof(string));
    
            var numeroCharlaParameter = numeroCharla.HasValue ?
                new ObjectParameter("NumeroCharla", numeroCharla) :
                new ObjectParameter("NumeroCharla", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarCharlaGrupal", id_CentroParameter, fechaInicialParameter, fechaFinalParameter, id_TipoCharlaParameter, id_NivelParameter, nrodeParticipantesParameter, id_UsuarioParameter, numeroCharlaParameter);
        }
    
        public virtual int ModificarCharlaGrupal(Nullable<int> id_CharlaGrupal, Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal, Nullable<int> id_TipoCharla, Nullable<int> id_Nivel, Nullable<int> nrodeParticipantes, string id_Usuario, Nullable<int> numeroCharla)
        {
            var id_CharlaGrupalParameter = id_CharlaGrupal.HasValue ?
                new ObjectParameter("Id_CharlaGrupal", id_CharlaGrupal) :
                new ObjectParameter("Id_CharlaGrupal", typeof(int));
    
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("FechaInicial", fechaInicial) :
                new ObjectParameter("FechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            var id_TipoCharlaParameter = id_TipoCharla.HasValue ?
                new ObjectParameter("Id_TipoCharla", id_TipoCharla) :
                new ObjectParameter("Id_TipoCharla", typeof(int));
    
            var id_NivelParameter = id_Nivel.HasValue ?
                new ObjectParameter("Id_Nivel", id_Nivel) :
                new ObjectParameter("Id_Nivel", typeof(int));
    
            var nrodeParticipantesParameter = nrodeParticipantes.HasValue ?
                new ObjectParameter("NrodeParticipantes", nrodeParticipantes) :
                new ObjectParameter("NrodeParticipantes", typeof(int));
    
            var id_UsuarioParameter = id_Usuario != null ?
                new ObjectParameter("Id_Usuario", id_Usuario) :
                new ObjectParameter("Id_Usuario", typeof(string));
    
            var numeroCharlaParameter = numeroCharla.HasValue ?
                new ObjectParameter("NumeroCharla", numeroCharla) :
                new ObjectParameter("NumeroCharla", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModificarCharlaGrupal", id_CharlaGrupalParameter, fechaInicialParameter, fechaFinalParameter, id_TipoCharlaParameter, id_NivelParameter, nrodeParticipantesParameter, id_UsuarioParameter, numeroCharlaParameter);
        }
    
        public virtual ObjectResult<ListarBalancedePagos_Result> ListarBalancedePagos(Nullable<int> id_Participante, Nullable<int> id_OrdenJudicial)
        {
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            var id_OrdenJudicialParameter = id_OrdenJudicial.HasValue ?
                new ObjectParameter("Id_OrdenJudicial", id_OrdenJudicial) :
                new ObjectParameter("Id_OrdenJudicial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarBalancedePagos_Result>("ListarBalancedePagos", id_ParticipanteParameter, id_OrdenJudicialParameter);
        }
    
        public virtual int GuardarOrdenJudicial(Nullable<int> id_Participante, string numeroOrdenJudicial, Nullable<int> id_UsuarioCreacion, Nullable<int> id_Programa)
        {
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            var numeroOrdenJudicialParameter = numeroOrdenJudicial != null ?
                new ObjectParameter("NumeroOrdenJudicial", numeroOrdenJudicial) :
                new ObjectParameter("NumeroOrdenJudicial", typeof(string));
    
            var id_UsuarioCreacionParameter = id_UsuarioCreacion.HasValue ?
                new ObjectParameter("Id_UsuarioCreacion", id_UsuarioCreacion) :
                new ObjectParameter("Id_UsuarioCreacion", typeof(int));
    
            var id_ProgramaParameter = id_Programa.HasValue ?
                new ObjectParameter("Id_Programa", id_Programa) :
                new ObjectParameter("Id_Programa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarOrdenJudicial", id_ParticipanteParameter, numeroOrdenJudicialParameter, id_UsuarioCreacionParameter, id_ProgramaParameter);
        }
    
        public virtual ObjectResult<ListarOrdenesJudicialesActivas_Result> ListarOrdenesJudicialesActivas(Nullable<int> id_Participante, Nullable<int> id_Programa)
        {
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            var id_ProgramaParameter = id_Programa.HasValue ?
                new ObjectParameter("Id_Programa", id_Programa) :
                new ObjectParameter("Id_Programa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarOrdenesJudicialesActivas_Result>("ListarOrdenesJudicialesActivas", id_ParticipanteParameter, id_ProgramaParameter);
        }
    
        public virtual int GuardarDocumentoPorParticipante(Nullable<int> id_Documento, Nullable<int> id_Participante, Nullable<int> id_OrdenJudicial, string pathNameDocumento, Nullable<int> id_UsuarioRecibe, Nullable<int> id_Programa)
        {
            var id_DocumentoParameter = id_Documento.HasValue ?
                new ObjectParameter("Id_Documento", id_Documento) :
                new ObjectParameter("Id_Documento", typeof(int));
    
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            var id_OrdenJudicialParameter = id_OrdenJudicial.HasValue ?
                new ObjectParameter("Id_OrdenJudicial", id_OrdenJudicial) :
                new ObjectParameter("Id_OrdenJudicial", typeof(int));
    
            var pathNameDocumentoParameter = pathNameDocumento != null ?
                new ObjectParameter("PathNameDocumento", pathNameDocumento) :
                new ObjectParameter("PathNameDocumento", typeof(string));
    
            var id_UsuarioRecibeParameter = id_UsuarioRecibe.HasValue ?
                new ObjectParameter("Id_UsuarioRecibe", id_UsuarioRecibe) :
                new ObjectParameter("Id_UsuarioRecibe", typeof(int));
    
            var id_ProgramaParameter = id_Programa.HasValue ?
                new ObjectParameter("Id_Programa", id_Programa) :
                new ObjectParameter("Id_Programa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarDocumentoPorParticipante", id_DocumentoParameter, id_ParticipanteParameter, id_OrdenJudicialParameter, pathNameDocumentoParameter, id_UsuarioRecibeParameter, id_ProgramaParameter);
        }
    
        public virtual ObjectResult<ListarDocumentosRecibidos_Result> ListarDocumentosRecibidos(Nullable<int> id_Participante, Nullable<int> id_Programa)
        {
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            var id_ProgramaParameter = id_Programa.HasValue ?
                new ObjectParameter("Id_Programa", id_Programa) :
                new ObjectParameter("Id_Programa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarDocumentosRecibidos_Result>("ListarDocumentosRecibidos", id_ParticipanteParameter, id_ProgramaParameter);
        }
    
        public virtual ObjectResult<ListarTipodeDocumentosPorParticipanteOrdenJudicial_Result> ListarTipodeDocumentosPorParticipanteOrdenJudicial(Nullable<int> id_OrdenJudicial, Nullable<int> id_Participante, Nullable<int> id_Programa)
        {
            var id_OrdenJudicialParameter = id_OrdenJudicial.HasValue ?
                new ObjectParameter("Id_OrdenJudicial", id_OrdenJudicial) :
                new ObjectParameter("Id_OrdenJudicial", typeof(int));
    
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            var id_ProgramaParameter = id_Programa.HasValue ?
                new ObjectParameter("Id_Programa", id_Programa) :
                new ObjectParameter("Id_Programa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarTipodeDocumentosPorParticipanteOrdenJudicial_Result>("ListarTipodeDocumentosPorParticipanteOrdenJudicial", id_OrdenJudicialParameter, id_ParticipanteParameter, id_ProgramaParameter);
        }
    
        public virtual ObjectResult<ListarCasosCriminalesActivos_Result> ListarCasosCriminalesActivos(Nullable<int> id_Participante, Nullable<int> id_Programa)
        {
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            var id_ProgramaParameter = id_Programa.HasValue ?
                new ObjectParameter("Id_Programa", id_Programa) :
                new ObjectParameter("Id_Programa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarCasosCriminalesActivos_Result>("ListarCasosCriminalesActivos", id_ParticipanteParameter, id_ProgramaParameter);
        }
    
        public virtual ObjectResult<ListarBalancedePagosCasosCriminales_Result> ListarBalancedePagosCasosCriminales(Nullable<int> id_Participante, Nullable<int> id_CasoCriminal)
        {
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            var id_CasoCriminalParameter = id_CasoCriminal.HasValue ?
                new ObjectParameter("Id_CasoCriminal", id_CasoCriminal) :
                new ObjectParameter("Id_CasoCriminal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarBalancedePagosCasosCriminales_Result>("ListarBalancedePagosCasosCriminales", id_ParticipanteParameter, id_CasoCriminalParameter);
        }
    
        public virtual int CerrarCasoCriminal(Nullable<int> id_CasoCriminal, Nullable<int> id_MotivoCierre, string comentarioCierre, string documentoAprobacion, string id_UsuarioCierre)
        {
            var id_CasoCriminalParameter = id_CasoCriminal.HasValue ?
                new ObjectParameter("Id_CasoCriminal", id_CasoCriminal) :
                new ObjectParameter("Id_CasoCriminal", typeof(int));
    
            var id_MotivoCierreParameter = id_MotivoCierre.HasValue ?
                new ObjectParameter("Id_MotivoCierre", id_MotivoCierre) :
                new ObjectParameter("Id_MotivoCierre", typeof(int));
    
            var comentarioCierreParameter = comentarioCierre != null ?
                new ObjectParameter("ComentarioCierre", comentarioCierre) :
                new ObjectParameter("ComentarioCierre", typeof(string));
    
            var documentoAprobacionParameter = documentoAprobacion != null ?
                new ObjectParameter("DocumentoAprobacion", documentoAprobacion) :
                new ObjectParameter("DocumentoAprobacion", typeof(string));
    
            var id_UsuarioCierreParameter = id_UsuarioCierre != null ?
                new ObjectParameter("Id_UsuarioCierre", id_UsuarioCierre) :
                new ObjectParameter("Id_UsuarioCierre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CerrarCasoCriminal", id_CasoCriminalParameter, id_MotivoCierreParameter, comentarioCierreParameter, documentoAprobacionParameter, id_UsuarioCierreParameter);
        }
    
        public virtual ObjectResult<ConsultarCasosXPersona_Result> ConsultarCasosXPersona(Nullable<int> pk_Persona)
        {
            var pk_PersonaParameter = pk_Persona.HasValue ?
                new ObjectParameter("Pk_Persona", pk_Persona) :
                new ObjectParameter("Pk_Persona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarCasosXPersona_Result>("ConsultarCasosXPersona", pk_PersonaParameter);
        }
    
        public virtual ObjectResult<BusquedaSencilladePersonasRecepcion_Result> BusquedaSencilladePersonasRecepcion(string nR_SeguroSocial, string identificacion, Nullable<System.DateTime> fE_Nacimiento, string nombre, string apellido, string segundoApellido, Nullable<short> fK_Programa)
        {
            var nR_SeguroSocialParameter = nR_SeguroSocial != null ?
                new ObjectParameter("NR_SeguroSocial", nR_SeguroSocial) :
                new ObjectParameter("NR_SeguroSocial", typeof(string));
    
            var identificacionParameter = identificacion != null ?
                new ObjectParameter("Identificacion", identificacion) :
                new ObjectParameter("Identificacion", typeof(string));
    
            var fE_NacimientoParameter = fE_Nacimiento.HasValue ?
                new ObjectParameter("FE_Nacimiento", fE_Nacimiento) :
                new ObjectParameter("FE_Nacimiento", typeof(System.DateTime));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            var segundoApellidoParameter = segundoApellido != null ?
                new ObjectParameter("SegundoApellido", segundoApellido) :
                new ObjectParameter("SegundoApellido", typeof(string));
    
            var fK_ProgramaParameter = fK_Programa.HasValue ?
                new ObjectParameter("FK_Programa", fK_Programa) :
                new ObjectParameter("FK_Programa", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BusquedaSencilladePersonasRecepcion_Result>("BusquedaSencilladePersonasRecepcion", nR_SeguroSocialParameter, identificacionParameter, fE_NacimientoParameter, nombreParameter, apellidoParameter, segundoApellidoParameter, fK_ProgramaParameter);
        }
    
        public virtual int GuardarExcepcionTrabajadorSocial(string id_TrabajadorSocial, Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal, Nullable<int> id_Programa)
        {
            var id_TrabajadorSocialParameter = id_TrabajadorSocial != null ?
                new ObjectParameter("Id_TrabajadorSocial", id_TrabajadorSocial) :
                new ObjectParameter("Id_TrabajadorSocial", typeof(string));
    
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("FechaInicial", fechaInicial) :
                new ObjectParameter("FechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            var id_ProgramaParameter = id_Programa.HasValue ?
                new ObjectParameter("Id_Programa", id_Programa) :
                new ObjectParameter("Id_Programa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarExcepcionTrabajadorSocial", id_TrabajadorSocialParameter, fechaInicialParameter, fechaFinalParameter, id_ProgramaParameter);
        }
    
        public virtual ObjectResult<ListarExcepcionesTrabajadorSocial_Result> ListarExcepcionesTrabajadorSocial(string id_TrabajadorSocial, Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal, Nullable<int> id_Programa)
        {
            var id_TrabajadorSocialParameter = id_TrabajadorSocial != null ?
                new ObjectParameter("Id_TrabajadorSocial", id_TrabajadorSocial) :
                new ObjectParameter("Id_TrabajadorSocial", typeof(string));
    
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("fechaInicial", fechaInicial) :
                new ObjectParameter("fechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            var id_ProgramaParameter = id_Programa.HasValue ?
                new ObjectParameter("Id_Programa", id_Programa) :
                new ObjectParameter("Id_Programa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarExcepcionesTrabajadorSocial_Result>("ListarExcepcionesTrabajadorSocial", id_TrabajadorSocialParameter, fechaInicialParameter, fechaFinalParameter, id_ProgramaParameter);
        }
    
        public virtual ObjectResult<ListarCargosCasosCriminales_Result> ListarCargosCasosCriminales(Nullable<int> fK_CasoCriminal)
        {
            var fK_CasoCriminalParameter = fK_CasoCriminal.HasValue ?
                new ObjectParameter("FK_CasoCriminal", fK_CasoCriminal) :
                new ObjectParameter("FK_CasoCriminal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarCargosCasosCriminales_Result>("ListarCargosCasosCriminales", fK_CasoCriminalParameter);
        }
    
        public virtual ObjectResult<ListarPagosCasosCriminales_Result> ListarPagosCasosCriminales(Nullable<int> fK_CasoCriminal)
        {
            var fK_CasoCriminalParameter = fK_CasoCriminal.HasValue ?
                new ObjectParameter("FK_CasoCriminal", fK_CasoCriminal) :
                new ObjectParameter("FK_CasoCriminal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarPagosCasosCriminales_Result>("ListarPagosCasosCriminales", fK_CasoCriminalParameter);
        }
    
        public virtual int GuardarCitaTrabajadorSocial(string id_TrabajadorSocial, Nullable<int> id_Participante, Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal, Nullable<int> id_OrdenJudicial, Nullable<int> id_Programa, string id_Usuario, Nullable<int> id_Precio)
        {
            var id_TrabajadorSocialParameter = id_TrabajadorSocial != null ?
                new ObjectParameter("Id_TrabajadorSocial", id_TrabajadorSocial) :
                new ObjectParameter("Id_TrabajadorSocial", typeof(string));
    
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("FechaInicial", fechaInicial) :
                new ObjectParameter("FechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            var id_OrdenJudicialParameter = id_OrdenJudicial.HasValue ?
                new ObjectParameter("Id_OrdenJudicial", id_OrdenJudicial) :
                new ObjectParameter("Id_OrdenJudicial", typeof(int));
    
            var id_ProgramaParameter = id_Programa.HasValue ?
                new ObjectParameter("Id_Programa", id_Programa) :
                new ObjectParameter("Id_Programa", typeof(int));
    
            var id_UsuarioParameter = id_Usuario != null ?
                new ObjectParameter("Id_Usuario", id_Usuario) :
                new ObjectParameter("Id_Usuario", typeof(string));
    
            var id_PrecioParameter = id_Precio.HasValue ?
                new ObjectParameter("Id_Precio", id_Precio) :
                new ObjectParameter("Id_Precio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarCitaTrabajadorSocial", id_TrabajadorSocialParameter, id_ParticipanteParameter, fechaInicialParameter, fechaFinalParameter, id_OrdenJudicialParameter, id_ProgramaParameter, id_UsuarioParameter, id_PrecioParameter);
        }
    
        public virtual ObjectResult<ConsultarCharlasPorParticipante_Result> ConsultarCharlasPorParticipante(Nullable<int> id_Participante)
        {
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarCharlasPorParticipante_Result>("ConsultarCharlasPorParticipante", id_ParticipanteParameter);
        }
    
        public virtual ObjectResult<ListarExcepcionesTrabajadorSocialAdmin_Result> ListarExcepcionesTrabajadorSocialAdmin(Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal, Nullable<int> id_Programa)
        {
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("fechaInicial", fechaInicial) :
                new ObjectParameter("fechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            var id_ProgramaParameter = id_Programa.HasValue ?
                new ObjectParameter("Id_Programa", id_Programa) :
                new ObjectParameter("Id_Programa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarExcepcionesTrabajadorSocialAdmin_Result>("ListarExcepcionesTrabajadorSocialAdmin", fechaInicialParameter, fechaFinalParameter, id_ProgramaParameter);
        }
    
        public virtual int GuardarDocumento(string documento, string archivo, Nullable<int> importante, Nullable<int> recurrente)
        {
            var documentoParameter = documento != null ?
                new ObjectParameter("Documento", documento) :
                new ObjectParameter("Documento", typeof(string));
    
            var archivoParameter = archivo != null ?
                new ObjectParameter("Archivo", archivo) :
                new ObjectParameter("Archivo", typeof(string));
    
            var importanteParameter = importante.HasValue ?
                new ObjectParameter("Importante", importante) :
                new ObjectParameter("Importante", typeof(int));
    
            var recurrenteParameter = recurrente.HasValue ?
                new ObjectParameter("Recurrente", recurrente) :
                new ObjectParameter("Recurrente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarDocumento", documentoParameter, archivoParameter, importanteParameter, recurrenteParameter);
        }
    
        public virtual int EliminarDocumentoActivo(Nullable<int> id_Documento)
        {
            var id_DocumentoParameter = id_Documento.HasValue ?
                new ObjectParameter("Id_Documento", id_Documento) :
                new ObjectParameter("Id_Documento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarDocumentoActivo", id_DocumentoParameter);
        }
    
        public virtual ObjectResult<ListarCasosCriminalesCompletados_Result> ListarCasosCriminalesCompletados(Nullable<int> id_Participante, Nullable<int> id_Programa)
        {
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            var id_ProgramaParameter = id_Programa.HasValue ?
                new ObjectParameter("Id_Programa", id_Programa) :
                new ObjectParameter("Id_Programa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarCasosCriminalesCompletados_Result>("ListarCasosCriminalesCompletados", id_ParticipanteParameter, id_ProgramaParameter);
        }
    
        public virtual ObjectResult<ConsultarCharlasParaTarjeta_Result> ConsultarCharlasParaTarjeta(Nullable<int> id_Participante, Nullable<int> fK_Programa)
        {
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            var fK_ProgramaParameter = fK_Programa.HasValue ?
                new ObjectParameter("FK_Programa", fK_Programa) :
                new ObjectParameter("FK_Programa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarCharlasParaTarjeta_Result>("ConsultarCharlasParaTarjeta", id_ParticipanteParameter, fK_ProgramaParameter);
        }
    
        public virtual int AsistieronTodosCharla(Nullable<int> id_CharlaGrupal)
        {
            var id_CharlaGrupalParameter = id_CharlaGrupal.HasValue ?
                new ObjectParameter("Id_CharlaGrupal", id_CharlaGrupal) :
                new ObjectParameter("Id_CharlaGrupal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AsistieronTodosCharla", id_CharlaGrupalParameter);
        }
    
        public virtual ObjectResult<ListarDocumentosRecibidosCasoCriminal_Result> ListarDocumentosRecibidosCasoCriminal(Nullable<int> id_Participante, Nullable<int> id_Programa, Nullable<int> id_CasoCriminal)
        {
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            var id_ProgramaParameter = id_Programa.HasValue ?
                new ObjectParameter("Id_Programa", id_Programa) :
                new ObjectParameter("Id_Programa", typeof(int));
    
            var id_CasoCriminalParameter = id_CasoCriminal.HasValue ?
                new ObjectParameter("Id_CasoCriminal", id_CasoCriminal) :
                new ObjectParameter("Id_CasoCriminal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarDocumentosRecibidosCasoCriminal_Result>("ListarDocumentosRecibidosCasoCriminal", id_ParticipanteParameter, id_ProgramaParameter, id_CasoCriminalParameter);
        }
    
        public virtual ObjectResult<BusquedaSencilladePersonasRecepcionExpediente_Result> BusquedaSencilladePersonasRecepcionExpediente(Nullable<short> fK_Programa, string nR_Expediente)
        {
            var fK_ProgramaParameter = fK_Programa.HasValue ?
                new ObjectParameter("FK_Programa", fK_Programa) :
                new ObjectParameter("FK_Programa", typeof(short));
    
            var nR_ExpedienteParameter = nR_Expediente != null ?
                new ObjectParameter("NR_Expediente", nR_Expediente) :
                new ObjectParameter("NR_Expediente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BusquedaSencilladePersonasRecepcionExpediente_Result>("BusquedaSencilladePersonasRecepcionExpediente", fK_ProgramaParameter, nR_ExpedienteParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> ListarAsistenciaCharlasImpacto(Nullable<int> id_Participante, Nullable<int> id_OrdenJudicial)
        {
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            var id_OrdenJudicialParameter = id_OrdenJudicial.HasValue ?
                new ObjectParameter("Id_OrdenJudicial", id_OrdenJudicial) :
                new ObjectParameter("Id_OrdenJudicial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ListarAsistenciaCharlasImpacto", id_ParticipanteParameter, id_OrdenJudicialParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> ListarAsistenciaCharlasRegulares(Nullable<int> id_Participante, Nullable<int> id_OrdenJudicial)
        {
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            var id_OrdenJudicialParameter = id_OrdenJudicial.HasValue ?
                new ObjectParameter("Id_OrdenJudicial", id_OrdenJudicial) :
                new ObjectParameter("Id_OrdenJudicial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ListarAsistenciaCharlasRegulares", id_ParticipanteParameter, id_OrdenJudicialParameter);
        }
    
        public virtual int GuardarCasoCriminal(Nullable<int> id_Participante, string numeroCasoCriminal, string numeroCasoCriminalDos, string numeroCasoCriminalTres, Nullable<System.DateTime> fechaOrden, Nullable<System.DateTime> fechaSentencia, string alcohol, Nullable<int> fK_Tribunal, string nB_Juez, string id_UsuarioCreacion, Nullable<int> fK_Programa, Nullable<int> numLicencia, Nullable<int> fK_EstadoCivil, string email, string telCelular, string telHogar, string telTrabajo, string direccionLinea1, string direccionLinea2, Nullable<int> fK_Pueblo, string codigoPostal, string direccionLinea1Postal, string direccionLinea2Postal, Nullable<int> fK_PuebloPostal, string codigoPostalPostal, Nullable<int> fK_PlanMedico, string condicionSalud, string impedimento, Nullable<int> fK_Grado, string lugarTrabajo, string ocupacion, Nullable<byte> veterano, Nullable<int> fK_DesempleoRazon, Nullable<int> cantidadFamilia, string nB_Pareja, string nB_Padre, string nB_Madre)
        {
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            var numeroCasoCriminalParameter = numeroCasoCriminal != null ?
                new ObjectParameter("NumeroCasoCriminal", numeroCasoCriminal) :
                new ObjectParameter("NumeroCasoCriminal", typeof(string));
    
            var numeroCasoCriminalDosParameter = numeroCasoCriminalDos != null ?
                new ObjectParameter("NumeroCasoCriminalDos", numeroCasoCriminalDos) :
                new ObjectParameter("NumeroCasoCriminalDos", typeof(string));
    
            var numeroCasoCriminalTresParameter = numeroCasoCriminalTres != null ?
                new ObjectParameter("NumeroCasoCriminalTres", numeroCasoCriminalTres) :
                new ObjectParameter("NumeroCasoCriminalTres", typeof(string));
    
            var fechaOrdenParameter = fechaOrden.HasValue ?
                new ObjectParameter("FechaOrden", fechaOrden) :
                new ObjectParameter("FechaOrden", typeof(System.DateTime));
    
            var fechaSentenciaParameter = fechaSentencia.HasValue ?
                new ObjectParameter("FechaSentencia", fechaSentencia) :
                new ObjectParameter("FechaSentencia", typeof(System.DateTime));
    
            var alcoholParameter = alcohol != null ?
                new ObjectParameter("Alcohol", alcohol) :
                new ObjectParameter("Alcohol", typeof(string));
    
            var fK_TribunalParameter = fK_Tribunal.HasValue ?
                new ObjectParameter("FK_Tribunal", fK_Tribunal) :
                new ObjectParameter("FK_Tribunal", typeof(int));
    
            var nB_JuezParameter = nB_Juez != null ?
                new ObjectParameter("NB_Juez", nB_Juez) :
                new ObjectParameter("NB_Juez", typeof(string));
    
            var id_UsuarioCreacionParameter = id_UsuarioCreacion != null ?
                new ObjectParameter("Id_UsuarioCreacion", id_UsuarioCreacion) :
                new ObjectParameter("Id_UsuarioCreacion", typeof(string));
    
            var fK_ProgramaParameter = fK_Programa.HasValue ?
                new ObjectParameter("FK_Programa", fK_Programa) :
                new ObjectParameter("FK_Programa", typeof(int));
    
            var numLicenciaParameter = numLicencia.HasValue ?
                new ObjectParameter("NumLicencia", numLicencia) :
                new ObjectParameter("NumLicencia", typeof(int));
    
            var fK_EstadoCivilParameter = fK_EstadoCivil.HasValue ?
                new ObjectParameter("FK_EstadoCivil", fK_EstadoCivil) :
                new ObjectParameter("FK_EstadoCivil", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var telCelularParameter = telCelular != null ?
                new ObjectParameter("TelCelular", telCelular) :
                new ObjectParameter("TelCelular", typeof(string));
    
            var telHogarParameter = telHogar != null ?
                new ObjectParameter("TelHogar", telHogar) :
                new ObjectParameter("TelHogar", typeof(string));
    
            var telTrabajoParameter = telTrabajo != null ?
                new ObjectParameter("TelTrabajo", telTrabajo) :
                new ObjectParameter("TelTrabajo", typeof(string));
    
            var direccionLinea1Parameter = direccionLinea1 != null ?
                new ObjectParameter("DireccionLinea1", direccionLinea1) :
                new ObjectParameter("DireccionLinea1", typeof(string));
    
            var direccionLinea2Parameter = direccionLinea2 != null ?
                new ObjectParameter("DireccionLinea2", direccionLinea2) :
                new ObjectParameter("DireccionLinea2", typeof(string));
    
            var fK_PuebloParameter = fK_Pueblo.HasValue ?
                new ObjectParameter("FK_Pueblo", fK_Pueblo) :
                new ObjectParameter("FK_Pueblo", typeof(int));
    
            var codigoPostalParameter = codigoPostal != null ?
                new ObjectParameter("CodigoPostal", codigoPostal) :
                new ObjectParameter("CodigoPostal", typeof(string));
    
            var direccionLinea1PostalParameter = direccionLinea1Postal != null ?
                new ObjectParameter("DireccionLinea1Postal", direccionLinea1Postal) :
                new ObjectParameter("DireccionLinea1Postal", typeof(string));
    
            var direccionLinea2PostalParameter = direccionLinea2Postal != null ?
                new ObjectParameter("DireccionLinea2Postal", direccionLinea2Postal) :
                new ObjectParameter("DireccionLinea2Postal", typeof(string));
    
            var fK_PuebloPostalParameter = fK_PuebloPostal.HasValue ?
                new ObjectParameter("FK_PuebloPostal", fK_PuebloPostal) :
                new ObjectParameter("FK_PuebloPostal", typeof(int));
    
            var codigoPostalPostalParameter = codigoPostalPostal != null ?
                new ObjectParameter("CodigoPostalPostal", codigoPostalPostal) :
                new ObjectParameter("CodigoPostalPostal", typeof(string));
    
            var fK_PlanMedicoParameter = fK_PlanMedico.HasValue ?
                new ObjectParameter("FK_PlanMedico", fK_PlanMedico) :
                new ObjectParameter("FK_PlanMedico", typeof(int));
    
            var condicionSaludParameter = condicionSalud != null ?
                new ObjectParameter("CondicionSalud", condicionSalud) :
                new ObjectParameter("CondicionSalud", typeof(string));
    
            var impedimentoParameter = impedimento != null ?
                new ObjectParameter("Impedimento", impedimento) :
                new ObjectParameter("Impedimento", typeof(string));
    
            var fK_GradoParameter = fK_Grado.HasValue ?
                new ObjectParameter("FK_Grado", fK_Grado) :
                new ObjectParameter("FK_Grado", typeof(int));
    
            var lugarTrabajoParameter = lugarTrabajo != null ?
                new ObjectParameter("LugarTrabajo", lugarTrabajo) :
                new ObjectParameter("LugarTrabajo", typeof(string));
    
            var ocupacionParameter = ocupacion != null ?
                new ObjectParameter("Ocupacion", ocupacion) :
                new ObjectParameter("Ocupacion", typeof(string));
    
            var veteranoParameter = veterano.HasValue ?
                new ObjectParameter("Veterano", veterano) :
                new ObjectParameter("Veterano", typeof(byte));
    
            var fK_DesempleoRazonParameter = fK_DesempleoRazon.HasValue ?
                new ObjectParameter("FK_DesempleoRazon", fK_DesempleoRazon) :
                new ObjectParameter("FK_DesempleoRazon", typeof(int));
    
            var cantidadFamiliaParameter = cantidadFamilia.HasValue ?
                new ObjectParameter("CantidadFamilia", cantidadFamilia) :
                new ObjectParameter("CantidadFamilia", typeof(int));
    
            var nB_ParejaParameter = nB_Pareja != null ?
                new ObjectParameter("NB_Pareja", nB_Pareja) :
                new ObjectParameter("NB_Pareja", typeof(string));
    
            var nB_PadreParameter = nB_Padre != null ?
                new ObjectParameter("NB_Padre", nB_Padre) :
                new ObjectParameter("NB_Padre", typeof(string));
    
            var nB_MadreParameter = nB_Madre != null ?
                new ObjectParameter("NB_Madre", nB_Madre) :
                new ObjectParameter("NB_Madre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarCasoCriminal", id_ParticipanteParameter, numeroCasoCriminalParameter, numeroCasoCriminalDosParameter, numeroCasoCriminalTresParameter, fechaOrdenParameter, fechaSentenciaParameter, alcoholParameter, fK_TribunalParameter, nB_JuezParameter, id_UsuarioCreacionParameter, fK_ProgramaParameter, numLicenciaParameter, fK_EstadoCivilParameter, emailParameter, telCelularParameter, telHogarParameter, telTrabajoParameter, direccionLinea1Parameter, direccionLinea2Parameter, fK_PuebloParameter, codigoPostalParameter, direccionLinea1PostalParameter, direccionLinea2PostalParameter, fK_PuebloPostalParameter, codigoPostalPostalParameter, fK_PlanMedicoParameter, condicionSaludParameter, impedimentoParameter, fK_GradoParameter, lugarTrabajoParameter, ocupacionParameter, veteranoParameter, fK_DesempleoRazonParameter, cantidadFamiliaParameter, nB_ParejaParameter, nB_PadreParameter, nB_MadreParameter);
        }
    
        public virtual int ModificarCasoCriminal(Nullable<int> id_CasoCriminal, string numeroCasoCriminal, string numeroCasoCriminalDos, string numeroCasoCriminalTres, Nullable<System.DateTime> fechaOrden, Nullable<System.DateTime> fechaSentencia, string alcohol, Nullable<int> fK_Tribunal, string nB_Juez, Nullable<int> numLicencia, Nullable<int> fK_EstadoCivil, string email, string telCelular, string telHogar, string telTrabajo, string direccionLinea1, string direccionLinea2, Nullable<int> fK_Pueblo, string codigoPostal, string direccionLinea1Postal, string direccionLinea2Postal, Nullable<int> fK_PuebloPostal, string codigoPostalPostal, Nullable<int> fK_PlanMedico, string condicionSalud, string impedimento, Nullable<int> fK_Grado, string lugarTrabajo, string ocupacion, Nullable<byte> veterano, Nullable<int> fK_DesempleoRazon, Nullable<int> cantidadFamilia, string nB_Pareja, string nB_Padre, string nB_Madre)
        {
            var id_CasoCriminalParameter = id_CasoCriminal.HasValue ?
                new ObjectParameter("Id_CasoCriminal", id_CasoCriminal) :
                new ObjectParameter("Id_CasoCriminal", typeof(int));
    
            var numeroCasoCriminalParameter = numeroCasoCriminal != null ?
                new ObjectParameter("NumeroCasoCriminal", numeroCasoCriminal) :
                new ObjectParameter("NumeroCasoCriminal", typeof(string));
    
            var numeroCasoCriminalDosParameter = numeroCasoCriminalDos != null ?
                new ObjectParameter("NumeroCasoCriminalDos", numeroCasoCriminalDos) :
                new ObjectParameter("NumeroCasoCriminalDos", typeof(string));
    
            var numeroCasoCriminalTresParameter = numeroCasoCriminalTres != null ?
                new ObjectParameter("NumeroCasoCriminalTres", numeroCasoCriminalTres) :
                new ObjectParameter("NumeroCasoCriminalTres", typeof(string));
    
            var fechaOrdenParameter = fechaOrden.HasValue ?
                new ObjectParameter("FechaOrden", fechaOrden) :
                new ObjectParameter("FechaOrden", typeof(System.DateTime));
    
            var fechaSentenciaParameter = fechaSentencia.HasValue ?
                new ObjectParameter("FechaSentencia", fechaSentencia) :
                new ObjectParameter("FechaSentencia", typeof(System.DateTime));
    
            var alcoholParameter = alcohol != null ?
                new ObjectParameter("Alcohol", alcohol) :
                new ObjectParameter("Alcohol", typeof(string));
    
            var fK_TribunalParameter = fK_Tribunal.HasValue ?
                new ObjectParameter("FK_Tribunal", fK_Tribunal) :
                new ObjectParameter("FK_Tribunal", typeof(int));
    
            var nB_JuezParameter = nB_Juez != null ?
                new ObjectParameter("NB_Juez", nB_Juez) :
                new ObjectParameter("NB_Juez", typeof(string));
    
            var numLicenciaParameter = numLicencia.HasValue ?
                new ObjectParameter("NumLicencia", numLicencia) :
                new ObjectParameter("NumLicencia", typeof(int));
    
            var fK_EstadoCivilParameter = fK_EstadoCivil.HasValue ?
                new ObjectParameter("FK_EstadoCivil", fK_EstadoCivil) :
                new ObjectParameter("FK_EstadoCivil", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var telCelularParameter = telCelular != null ?
                new ObjectParameter("TelCelular", telCelular) :
                new ObjectParameter("TelCelular", typeof(string));
    
            var telHogarParameter = telHogar != null ?
                new ObjectParameter("TelHogar", telHogar) :
                new ObjectParameter("TelHogar", typeof(string));
    
            var telTrabajoParameter = telTrabajo != null ?
                new ObjectParameter("TelTrabajo", telTrabajo) :
                new ObjectParameter("TelTrabajo", typeof(string));
    
            var direccionLinea1Parameter = direccionLinea1 != null ?
                new ObjectParameter("DireccionLinea1", direccionLinea1) :
                new ObjectParameter("DireccionLinea1", typeof(string));
    
            var direccionLinea2Parameter = direccionLinea2 != null ?
                new ObjectParameter("DireccionLinea2", direccionLinea2) :
                new ObjectParameter("DireccionLinea2", typeof(string));
    
            var fK_PuebloParameter = fK_Pueblo.HasValue ?
                new ObjectParameter("FK_Pueblo", fK_Pueblo) :
                new ObjectParameter("FK_Pueblo", typeof(int));
    
            var codigoPostalParameter = codigoPostal != null ?
                new ObjectParameter("CodigoPostal", codigoPostal) :
                new ObjectParameter("CodigoPostal", typeof(string));
    
            var direccionLinea1PostalParameter = direccionLinea1Postal != null ?
                new ObjectParameter("DireccionLinea1Postal", direccionLinea1Postal) :
                new ObjectParameter("DireccionLinea1Postal", typeof(string));
    
            var direccionLinea2PostalParameter = direccionLinea2Postal != null ?
                new ObjectParameter("DireccionLinea2Postal", direccionLinea2Postal) :
                new ObjectParameter("DireccionLinea2Postal", typeof(string));
    
            var fK_PuebloPostalParameter = fK_PuebloPostal.HasValue ?
                new ObjectParameter("FK_PuebloPostal", fK_PuebloPostal) :
                new ObjectParameter("FK_PuebloPostal", typeof(int));
    
            var codigoPostalPostalParameter = codigoPostalPostal != null ?
                new ObjectParameter("CodigoPostalPostal", codigoPostalPostal) :
                new ObjectParameter("CodigoPostalPostal", typeof(string));
    
            var fK_PlanMedicoParameter = fK_PlanMedico.HasValue ?
                new ObjectParameter("FK_PlanMedico", fK_PlanMedico) :
                new ObjectParameter("FK_PlanMedico", typeof(int));
    
            var condicionSaludParameter = condicionSalud != null ?
                new ObjectParameter("CondicionSalud", condicionSalud) :
                new ObjectParameter("CondicionSalud", typeof(string));
    
            var impedimentoParameter = impedimento != null ?
                new ObjectParameter("Impedimento", impedimento) :
                new ObjectParameter("Impedimento", typeof(string));
    
            var fK_GradoParameter = fK_Grado.HasValue ?
                new ObjectParameter("FK_Grado", fK_Grado) :
                new ObjectParameter("FK_Grado", typeof(int));
    
            var lugarTrabajoParameter = lugarTrabajo != null ?
                new ObjectParameter("LugarTrabajo", lugarTrabajo) :
                new ObjectParameter("LugarTrabajo", typeof(string));
    
            var ocupacionParameter = ocupacion != null ?
                new ObjectParameter("Ocupacion", ocupacion) :
                new ObjectParameter("Ocupacion", typeof(string));
    
            var veteranoParameter = veterano.HasValue ?
                new ObjectParameter("Veterano", veterano) :
                new ObjectParameter("Veterano", typeof(byte));
    
            var fK_DesempleoRazonParameter = fK_DesempleoRazon.HasValue ?
                new ObjectParameter("FK_DesempleoRazon", fK_DesempleoRazon) :
                new ObjectParameter("FK_DesempleoRazon", typeof(int));
    
            var cantidadFamiliaParameter = cantidadFamilia.HasValue ?
                new ObjectParameter("CantidadFamilia", cantidadFamilia) :
                new ObjectParameter("CantidadFamilia", typeof(int));
    
            var nB_ParejaParameter = nB_Pareja != null ?
                new ObjectParameter("NB_Pareja", nB_Pareja) :
                new ObjectParameter("NB_Pareja", typeof(string));
    
            var nB_PadreParameter = nB_Padre != null ?
                new ObjectParameter("NB_Padre", nB_Padre) :
                new ObjectParameter("NB_Padre", typeof(string));
    
            var nB_MadreParameter = nB_Madre != null ?
                new ObjectParameter("NB_Madre", nB_Madre) :
                new ObjectParameter("NB_Madre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModificarCasoCriminal", id_CasoCriminalParameter, numeroCasoCriminalParameter, numeroCasoCriminalDosParameter, numeroCasoCriminalTresParameter, fechaOrdenParameter, fechaSentenciaParameter, alcoholParameter, fK_TribunalParameter, nB_JuezParameter, numLicenciaParameter, fK_EstadoCivilParameter, emailParameter, telCelularParameter, telHogarParameter, telTrabajoParameter, direccionLinea1Parameter, direccionLinea2Parameter, fK_PuebloParameter, codigoPostalParameter, direccionLinea1PostalParameter, direccionLinea2PostalParameter, fK_PuebloPostalParameter, codigoPostalPostalParameter, fK_PlanMedicoParameter, condicionSaludParameter, impedimentoParameter, fK_GradoParameter, lugarTrabajoParameter, ocupacionParameter, veteranoParameter, fK_DesempleoRazonParameter, cantidadFamiliaParameter, nB_ParejaParameter, nB_PadreParameter, nB_MadreParameter);
        }
    
        public virtual ObjectResult<ListarParticipantesPorCharlasCasoCriminal_Result> ListarParticipantesPorCharlasCasoCriminal(Nullable<int> id_CharlaGrupal)
        {
            var id_CharlaGrupalParameter = id_CharlaGrupal.HasValue ?
                new ObjectParameter("Id_CharlaGrupal", id_CharlaGrupal) :
                new ObjectParameter("Id_CharlaGrupal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarParticipantesPorCharlasCasoCriminal_Result>("ListarParticipantesPorCharlasCasoCriminal", id_CharlaGrupalParameter);
        }
    
        public virtual int EliminarParticipanteCharlaGrupalCasoCriminal(Nullable<int> id_CharlaGrupal, Nullable<int> id_Participante, Nullable<int> casoCriminal)
        {
            var id_CharlaGrupalParameter = id_CharlaGrupal.HasValue ?
                new ObjectParameter("Id_CharlaGrupal", id_CharlaGrupal) :
                new ObjectParameter("Id_CharlaGrupal", typeof(int));
    
            var id_ParticipanteParameter = id_Participante.HasValue ?
                new ObjectParameter("Id_Participante", id_Participante) :
                new ObjectParameter("Id_Participante", typeof(int));
    
            var casoCriminalParameter = casoCriminal.HasValue ?
                new ObjectParameter("CasoCriminal", casoCriminal) :
                new ObjectParameter("CasoCriminal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarParticipanteCharlaGrupalCasoCriminal", id_CharlaGrupalParameter, id_ParticipanteParameter, casoCriminalParameter);
        }
    
        public virtual int RegistrarPago(Nullable<int> fK_CasoCriminal, string fK_Usuario, Nullable<System.DateTime> fechaTransaccion, Nullable<int> fK_FormadePago, Nullable<decimal> cantidad, string numeroRecibo, Nullable<long> numerodeCheque, string descripcion)
        {
            var fK_CasoCriminalParameter = fK_CasoCriminal.HasValue ?
                new ObjectParameter("FK_CasoCriminal", fK_CasoCriminal) :
                new ObjectParameter("FK_CasoCriminal", typeof(int));
    
            var fK_UsuarioParameter = fK_Usuario != null ?
                new ObjectParameter("FK_Usuario", fK_Usuario) :
                new ObjectParameter("FK_Usuario", typeof(string));
    
            var fechaTransaccionParameter = fechaTransaccion.HasValue ?
                new ObjectParameter("FechaTransaccion", fechaTransaccion) :
                new ObjectParameter("FechaTransaccion", typeof(System.DateTime));
    
            var fK_FormadePagoParameter = fK_FormadePago.HasValue ?
                new ObjectParameter("FK_FormadePago", fK_FormadePago) :
                new ObjectParameter("FK_FormadePago", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(decimal));
    
            var numeroReciboParameter = numeroRecibo != null ?
                new ObjectParameter("NumeroRecibo", numeroRecibo) :
                new ObjectParameter("NumeroRecibo", typeof(string));
    
            var numerodeChequeParameter = numerodeCheque.HasValue ?
                new ObjectParameter("NumerodeCheque", numerodeCheque) :
                new ObjectParameter("NumerodeCheque", typeof(long));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegistrarPago", fK_CasoCriminalParameter, fK_UsuarioParameter, fechaTransaccionParameter, fK_FormadePagoParameter, cantidadParameter, numeroReciboParameter, numerodeChequeParameter, descripcionParameter);
        }
    
        public virtual int RegistrarVoidPago(Nullable<int> pK_ControlPago, Nullable<int> fK_CasoCriminal, string fK_Usuario, Nullable<decimal> cantidad, string numeroRecibo, Nullable<long> numerodeCheque, string descripcion, string voidDesc)
        {
            var pK_ControlPagoParameter = pK_ControlPago.HasValue ?
                new ObjectParameter("PK_ControlPago", pK_ControlPago) :
                new ObjectParameter("PK_ControlPago", typeof(int));
    
            var fK_CasoCriminalParameter = fK_CasoCriminal.HasValue ?
                new ObjectParameter("FK_CasoCriminal", fK_CasoCriminal) :
                new ObjectParameter("FK_CasoCriminal", typeof(int));
    
            var fK_UsuarioParameter = fK_Usuario != null ?
                new ObjectParameter("FK_Usuario", fK_Usuario) :
                new ObjectParameter("FK_Usuario", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(decimal));
    
            var numeroReciboParameter = numeroRecibo != null ?
                new ObjectParameter("NumeroRecibo", numeroRecibo) :
                new ObjectParameter("NumeroRecibo", typeof(string));
    
            var numerodeChequeParameter = numerodeCheque.HasValue ?
                new ObjectParameter("NumerodeCheque", numerodeCheque) :
                new ObjectParameter("NumerodeCheque", typeof(long));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var voidDescParameter = voidDesc != null ?
                new ObjectParameter("VoidDesc", voidDesc) :
                new ObjectParameter("VoidDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegistrarVoidPago", pK_ControlPagoParameter, fK_CasoCriminalParameter, fK_UsuarioParameter, cantidadParameter, numeroReciboParameter, numerodeChequeParameter, descripcionParameter, voidDescParameter);
        }
    
        public virtual ObjectResult<ListarCharlasCasoCriminal_Result> ListarCharlasCasoCriminal(Nullable<int> casoCriminal)
        {
            var casoCriminalParameter = casoCriminal.HasValue ?
                new ObjectParameter("CasoCriminal", casoCriminal) :
                new ObjectParameter("CasoCriminal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarCharlasCasoCriminal_Result>("ListarCharlasCasoCriminal", casoCriminalParameter);
        }
    
        public virtual int ReabrirCasoCriminal(Nullable<int> id_CasoCriminal)
        {
            var id_CasoCriminalParameter = id_CasoCriminal.HasValue ?
                new ObjectParameter("Id_CasoCriminal", id_CasoCriminal) :
                new ObjectParameter("Id_CasoCriminal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ReabrirCasoCriminal", id_CasoCriminalParameter);
        }
    }
}
