//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ley22_WebApp_V2.Old_App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenesJudiciale
    {
        public int Id_OrdenJudicial { get; set; }
        public int Id_Participante { get; set; }
        public string NumeroOrdenJudicial { get; set; }
        public int Activa { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int Id_UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public Nullable<int> Id_MotivoCierre { get; set; }
        public string ComentarioCierre { get; set; }
        public string DocumentoAprobacion { get; set; }
        public Nullable<int> Id_UsuarioCierre { get; set; }
    }
}
