//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ley22_WebApp_V2.Old_App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipantesPorCharla
    {
        public int Id_ParticipantePorCharlaGrupal { get; set; }
        public int Id_CharlaGrupal { get; set; }
        public int Id_Participante { get; set; }
        public string Id_Usuario { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int Asistio { get; set; }
        public Nullable<int> Id_OrdenJudicial { get; set; }
    }
}
