//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ley22_WebApp_V2.Old_App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participante
    {
        public int Id_Participante { get; set; }
        public string Identificacion { get; set; }
        public string Pasaporte { get; set; }
        public string Licencia { get; set; }
        public Nullable<int> IUP { get; set; }
        public string Expediente { get; set; }
        public string Correo { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string TelefonoFamiliarMasCercano { get; set; }
        public string TelefonoCitas { get; set; }
        public string DireccionLinea1 { get; set; }
        public string DireccionLinea2 { get; set; }
        public string Municipio { get; set; }
        public string CodigoPostal { get; set; }
        public System.DateTime FE_Edicion { get; set; }
        public Nullable<int> Fk_UsuarioEdicion { get; set; }
    }
}
