//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ley22_WebApp_V2.Old_App_Code
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SEPSEntities1 : DbContext
    {
        public SEPSEntities1()
            : base("name=SEPSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SA_LKP_ABUSO_SUSTANCIAS> SA_LKP_ABUSO_SUSTANCIAS { get; set; }
        public virtual DbSet<SA_LKP_ALTA> SA_LKP_ALTA { get; set; }
        public virtual DbSet<SA_LKP_COMPOSICION_FAMILIAR> SA_LKP_COMPOSICION_FAMILIAR { get; set; }
        public virtual DbSet<SA_LKP_DIAGNOSTICO> SA_LKP_DIAGNOSTICO { get; set; }
        public virtual DbSet<SA_LKP_DSMIV_CAT> SA_LKP_DSMIV_CAT { get; set; }
        public virtual DbSet<SA_LKP_DSMIV_IV> SA_LKP_DSMIV_IV { get; set; }
        public virtual DbSet<SA_LKP_DSMV> SA_LKP_DSMV { get; set; }
        public virtual DbSet<SA_LKP_DSMV_ProblemasPsicosocialesAmbientales> SA_LKP_DSMV_ProblemasPsicosocialesAmbientales { get; set; }
        public virtual DbSet<SA_LKP_FEMINA> SA_LKP_FEMINA { get; set; }
        public virtual DbSet<SA_LKP_INGRESO_ANUAL> SA_LKP_INGRESO_ANUAL { get; set; }
        public virtual DbSet<SA_LKP_MEDIDA> SA_LKP_MEDIDA { get; set; }
        public virtual DbSet<SA_LKP_MUNICIPIO_RESIDENCIA> SA_LKP_MUNICIPIO_RESIDENCIA { get; set; }
        public virtual DbSet<SA_LKP_PROBLEMA_JUSTICIA> SA_LKP_PROBLEMA_JUSTICIA { get; set; }
        public virtual DbSet<SA_LKP_REFERIDOS_TX> SA_LKP_REFERIDOS_TX { get; set; }
        public virtual DbSet<SA_LKP_SALUD_MENTAL> SA_LKP_SALUD_MENTAL { get; set; }
        public virtual DbSet<SA_LKP_TEDS_COND_LABORAL> SA_LKP_TEDS_COND_LABORAL { get; set; }
        public virtual DbSet<SA_LKP_TEDS_EPISODIO_PREVIO> SA_LKP_TEDS_EPISODIO_PREVIO { get; set; }
        public virtual DbSet<SA_LKP_TEDS_ESTADO_LEGAL> SA_LKP_TEDS_ESTADO_LEGAL { get; set; }
        public virtual DbSet<SA_LKP_TEDS_ESTADO_MARITAL> SA_LKP_TEDS_ESTADO_MARITAL { get; set; }
        public virtual DbSet<SA_LKP_TEDS_ETAPA_SERVICIO> SA_LKP_TEDS_ETAPA_SERVICIO { get; set; }
        public virtual DbSet<SA_LKP_TEDS_FRECUENCIA> SA_LKP_TEDS_FRECUENCIA { get; set; }
        public virtual DbSet<SA_LKP_TEDS_FRECUENCIA_AUTOAYUDA> SA_LKP_TEDS_FRECUENCIA_AUTOAYUDA { get; set; }
        public virtual DbSet<SA_LKP_TEDS_FUENTE_INGRESO> SA_LKP_TEDS_FUENTE_INGRESO { get; set; }
        public virtual DbSet<SA_LKP_TEDS_GRADO> SA_LKP_TEDS_GRADO { get; set; }
        public virtual DbSet<SA_LKP_TEDS_NO_FUERZA_LABORAL> SA_LKP_TEDS_NO_FUERZA_LABORAL { get; set; }
        public virtual DbSet<SA_LKP_TEDS_PAGO> SA_LKP_TEDS_PAGO { get; set; }
        public virtual DbSet<SA_LKP_TEDS_RAZA> SA_LKP_TEDS_RAZA { get; set; }
        public virtual DbSet<SA_LKP_TEDS_REFERIDO> SA_LKP_TEDS_REFERIDO { get; set; }
        public virtual DbSet<SA_LKP_TEDS_RESIDENCIA> SA_LKP_TEDS_RESIDENCIA { get; set; }
        public virtual DbSet<SA_LKP_TEDS_SEGURO_SALUD> SA_LKP_TEDS_SEGURO_SALUD { get; set; }
        public virtual DbSet<SA_LKP_TEDS_SITUACION_ESCOLAR> SA_LKP_TEDS_SITUACION_ESCOLAR { get; set; }
        public virtual DbSet<SA_LKP_TEDS_SUSTANCIA> SA_LKP_TEDS_SUSTANCIA { get; set; }
        public virtual DbSet<SA_LKP_TEDS_TIPO_ADMISION> SA_LKP_TEDS_TIPO_ADMISION { get; set; }
        public virtual DbSet<SA_LKP_TEDS_VIA_UTILIZACION> SA_LKP_TEDS_VIA_UTILIZACION { get; set; }
        public virtual DbSet<SA_LKP_TIEMPO_RESIDENCIA> SA_LKP_TIEMPO_RESIDENCIA { get; set; }
        public virtual DbSet<SA_LKP_TIEMPO_ULT_TRAT> SA_LKP_TIEMPO_ULT_TRAT { get; set; }
        public virtual DbSet<SA_PROGRAMA> SA_PROGRAMA { get; set; }
        public virtual DbSet<VW_EPISODIO> VW_EPISODIO { get; set; }
        public virtual DbSet<VW_PERFIL> VW_PERFIL { get; set; }
        public virtual DbSet<VW_PERSONA> VW_PERSONA { get; set; }
        public virtual DbSet<SA_LKP_GENERO> SA_LKP_GENERO { get; set; }
        public virtual DbSet<SA_LKP_MILITAR> SA_LKP_MILITAR { get; set; }
        public virtual DbSet<SA_NewData> SA_NewData { get; set; }
        public virtual DbSet<SA_Ref_CompFamilia> SA_Ref_CompFamilia { get; set; }
        public virtual DbSet<SA_Ref_Maltrato> SA_Ref_Maltrato { get; set; }
        public virtual DbSet<SA_LKP_MALTRATO> SA_LKP_MALTRATO { get; set; }
        public virtual DbSet<SA_Ref_ProbJusticia> SA_Ref_ProbJusticia { get; set; }
        public virtual DbSet<SA_LKP_PracticasBasadasEnEvidencia> SA_LKP_PracticasBasadasEnEvidencia { get; set; }
        public virtual DbSet<SA_Ref_PracticasBasadasEnEvidencia> SA_Ref_PracticasBasadasEnEvidencia { get; set; }
        public virtual DbSet<SA_Ref_CondicionesDiagnosticadas> SA_Ref_CondicionesDiagnosticadas { get; set; }
        public virtual DbSet<SA_LKP_TakeHomeFrecuenciaBotellas> SA_LKP_TakeHomeFrecuenciaBotellas { get; set; }
        public virtual DbSet<SA_Metadona> SA_Metadona { get; set; }
        public virtual DbSet<SA_LKP_RAZONTH> SA_LKP_RAZONTH { get; set; }
        public virtual DbSet<SA_Ref_RazonTH> SA_Ref_RazonTH { get; set; }
        public virtual DbSet<SA_LKP_CATEGORIAS_CENTROS_PRIVADOS> SA_LKP_CATEGORIAS_CENTROS_PRIVADOS { get; set; }
        public virtual DbSet<SA_PERSONA_PROGRAMA> SA_PERSONA_PROGRAMA { get; set; }
    
        public virtual ObjectResult<SPR_PERFILES_LEY22_Result> SPR_PERFILES_LEY22(Nullable<int> pK_Episodio)
        {
            var pK_EpisodioParameter = pK_Episodio.HasValue ?
                new ObjectParameter("PK_Episodio", pK_Episodio) :
                new ObjectParameter("PK_Episodio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPR_PERFILES_LEY22_Result>("SPR_PERFILES_LEY22", pK_EpisodioParameter);
        }
    
        public virtual int SPC_PERSONA(string nR_SeguroSocial, Nullable<short> pK_Programa, string nR_Expediente, Nullable<byte> fK_Sexo, string aP_Primero, string aP_Segundo, string nB_Primero, string nB_Segundo, Nullable<System.DateTime> fE_Nacimiento, Nullable<byte> fK_Veterano, Nullable<byte> fK_GrupoEtnico, Nullable<System.Guid> fK_Sesion, ObjectParameter pK_Persona)
        {
            var nR_SeguroSocialParameter = nR_SeguroSocial != null ?
                new ObjectParameter("NR_SeguroSocial", nR_SeguroSocial) :
                new ObjectParameter("NR_SeguroSocial", typeof(string));
    
            var pK_ProgramaParameter = pK_Programa.HasValue ?
                new ObjectParameter("PK_Programa", pK_Programa) :
                new ObjectParameter("PK_Programa", typeof(short));
    
            var nR_ExpedienteParameter = nR_Expediente != null ?
                new ObjectParameter("NR_Expediente", nR_Expediente) :
                new ObjectParameter("NR_Expediente", typeof(string));
    
            var fK_SexoParameter = fK_Sexo.HasValue ?
                new ObjectParameter("FK_Sexo", fK_Sexo) :
                new ObjectParameter("FK_Sexo", typeof(byte));
    
            var aP_PrimeroParameter = aP_Primero != null ?
                new ObjectParameter("AP_Primero", aP_Primero) :
                new ObjectParameter("AP_Primero", typeof(string));
    
            var aP_SegundoParameter = aP_Segundo != null ?
                new ObjectParameter("AP_Segundo", aP_Segundo) :
                new ObjectParameter("AP_Segundo", typeof(string));
    
            var nB_PrimeroParameter = nB_Primero != null ?
                new ObjectParameter("NB_Primero", nB_Primero) :
                new ObjectParameter("NB_Primero", typeof(string));
    
            var nB_SegundoParameter = nB_Segundo != null ?
                new ObjectParameter("NB_Segundo", nB_Segundo) :
                new ObjectParameter("NB_Segundo", typeof(string));
    
            var fE_NacimientoParameter = fE_Nacimiento.HasValue ?
                new ObjectParameter("FE_Nacimiento", fE_Nacimiento) :
                new ObjectParameter("FE_Nacimiento", typeof(System.DateTime));
    
            var fK_VeteranoParameter = fK_Veterano.HasValue ?
                new ObjectParameter("FK_Veterano", fK_Veterano) :
                new ObjectParameter("FK_Veterano", typeof(byte));
    
            var fK_GrupoEtnicoParameter = fK_GrupoEtnico.HasValue ?
                new ObjectParameter("FK_GrupoEtnico", fK_GrupoEtnico) :
                new ObjectParameter("FK_GrupoEtnico", typeof(byte));
    
            var fK_SesionParameter = fK_Sesion.HasValue ?
                new ObjectParameter("FK_Sesion", fK_Sesion) :
                new ObjectParameter("FK_Sesion", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPC_PERSONA", nR_SeguroSocialParameter, pK_ProgramaParameter, nR_ExpedienteParameter, fK_SexoParameter, aP_PrimeroParameter, aP_SegundoParameter, nB_PrimeroParameter, nB_SegundoParameter, fE_NacimientoParameter, fK_VeteranoParameter, fK_GrupoEtnicoParameter, fK_SesionParameter, pK_Persona);
        }
    
        public virtual int SPU_PERSONA(Nullable<int> pK_Persona, Nullable<short> fK_Programa, string nR_Expediente, string nR_SeguroSocial, Nullable<byte> fK_Sexo, string aP_Primero, string aP_Segundo, string nB_Primero, string nB_Segundo, Nullable<System.DateTime> fE_Nacimiento, string fK_Veterano, string fK_GrupoEtnico, Nullable<System.Guid> fK_Sesion)
        {
            var pK_PersonaParameter = pK_Persona.HasValue ?
                new ObjectParameter("PK_Persona", pK_Persona) :
                new ObjectParameter("PK_Persona", typeof(int));
    
            var fK_ProgramaParameter = fK_Programa.HasValue ?
                new ObjectParameter("FK_Programa", fK_Programa) :
                new ObjectParameter("FK_Programa", typeof(short));
    
            var nR_ExpedienteParameter = nR_Expediente != null ?
                new ObjectParameter("NR_Expediente", nR_Expediente) :
                new ObjectParameter("NR_Expediente", typeof(string));
    
            var nR_SeguroSocialParameter = nR_SeguroSocial != null ?
                new ObjectParameter("NR_SeguroSocial", nR_SeguroSocial) :
                new ObjectParameter("NR_SeguroSocial", typeof(string));
    
            var fK_SexoParameter = fK_Sexo.HasValue ?
                new ObjectParameter("FK_Sexo", fK_Sexo) :
                new ObjectParameter("FK_Sexo", typeof(byte));
    
            var aP_PrimeroParameter = aP_Primero != null ?
                new ObjectParameter("AP_Primero", aP_Primero) :
                new ObjectParameter("AP_Primero", typeof(string));
    
            var aP_SegundoParameter = aP_Segundo != null ?
                new ObjectParameter("AP_Segundo", aP_Segundo) :
                new ObjectParameter("AP_Segundo", typeof(string));
    
            var nB_PrimeroParameter = nB_Primero != null ?
                new ObjectParameter("NB_Primero", nB_Primero) :
                new ObjectParameter("NB_Primero", typeof(string));
    
            var nB_SegundoParameter = nB_Segundo != null ?
                new ObjectParameter("NB_Segundo", nB_Segundo) :
                new ObjectParameter("NB_Segundo", typeof(string));
    
            var fE_NacimientoParameter = fE_Nacimiento.HasValue ?
                new ObjectParameter("FE_Nacimiento", fE_Nacimiento) :
                new ObjectParameter("FE_Nacimiento", typeof(System.DateTime));
    
            var fK_VeteranoParameter = fK_Veterano != null ?
                new ObjectParameter("FK_Veterano", fK_Veterano) :
                new ObjectParameter("FK_Veterano", typeof(string));
    
            var fK_GrupoEtnicoParameter = fK_GrupoEtnico != null ?
                new ObjectParameter("FK_GrupoEtnico", fK_GrupoEtnico) :
                new ObjectParameter("FK_GrupoEtnico", typeof(string));
    
            var fK_SesionParameter = fK_Sesion.HasValue ?
                new ObjectParameter("FK_Sesion", fK_Sesion) :
                new ObjectParameter("FK_Sesion", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPU_PERSONA", pK_PersonaParameter, fK_ProgramaParameter, nR_ExpedienteParameter, nR_SeguroSocialParameter, fK_SexoParameter, aP_PrimeroParameter, aP_SegundoParameter, nB_PrimeroParameter, nB_SegundoParameter, fE_NacimientoParameter, fK_VeteranoParameter, fK_GrupoEtnicoParameter, fK_SesionParameter);
        }
    }
}
