//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Ley22_WebApp_V2.AppCode
{
    //using System;
    //using System.Collections.Generic;

    //public partial class SA_LKP_ABUSO_SUSTANCIAS
    //{
    //    public byte PK_AbusoSustancias { get; set; }
    //    public string CO_TEDS { get; set; }
    //    public string DE_AbusoSustancias { get; set; }
    //    public Nullable<bool> Active { get; set; }
    //    public Nullable<int> Ordered { get; set; }
    //    public Nullable<bool> ServiceReportsToTEDS_SA { get; set; }
    //}

    //public partial class SA_LKP_ALTA
    //{
    //    public byte PK_Alta { get; set; }
    //    public string DE_Alta { get; set; }
    //    public string CO_TEDS { get; set; }
    //    public string CO_TEDS_MH { get; set; }
    //    public Nullable<bool> Active { get; set; }
    //    public Nullable<int> Ordered { get; set; }
    //}

    //public partial class SA_LKP_COMPOSICION_FAMILIAR
    //{
    //    public byte PK_Familiar { get; set; }
    //    public string DE_Familiar { get; set; }
    //    public Nullable<bool> Active { get; set; }
    //    public Nullable<int> Ordered { get; set; }
    //}

    //public partial class SA_LKP_DIAGNOSTICO
    //{
    //    public byte PK_Diagnostico { get; set; }
    //    public string DE_Diagnostico { get; set; }
    //    public Nullable<bool> Active { get; set; }
    //    public Nullable<int> Ordered { get; set; }
    //}

    //public partial class SA_LKP_DSMIV_CAT
    //{
    //    public byte PK_DSMIVCat { get; set; }
    //    public string DE_DSMIVCat { get; set; }
    //}

    //public partial class SA_LKP_DSMIV_IV
    //{
    //    public byte PK_DSMIV_IV { get; set; }
    //    public string DE_DSMIV_IV { get; set; }
    //}

    //public partial class SA_LKP_DSMV
    //{
    //    public short C_PK_DSMV { get; set; }
    //    public string PK_DSMV { get; set; }
    //    public string DE_DSMV { get; set; }
    //}

    //public partial class SA_LKP_DSMV_ProblemasPsicosocialesAmbientales
    //{
    //    public byte PK_DSMV_ProblemasPsicosocialesAmbientales { get; set; }
    //    public string DE_DSMV_ProblemasPsicosocialesAmbientales { get; set; }
    //}

    //public partial class SA_LKP_FEMINA
    //{
    //    public byte PK_Femina { get; set; }
    //    public string DE_Femina { get; set; }
    //    public Nullable<byte> CO_TEDS { get; set; }
    //    public Nullable<bool> Active { get; set; }
    //    public Nullable<int> Ordered { get; set; }
    //}

    //public partial class SA_LKP_GENERO
    //{
    //    public int PK_Genero { get; set; }
    //    public string DE_Genero { get; set; }
    //    public Nullable<bool> Active { get; set; }
    //    public Nullable<int> Ordered { get; set; }
    //}

    //public partial class SA_LKP_INGRESO_ANUAL
    //{
    //    public byte PK_IngresoAnual { get; set; }
    //    public string DE_IngresoAnual { get; set; }
    //}

    //public partial class SA_LKP_MEDIDA
    //{
    //    public byte PK_Medida { get; set; }
    //    public string DE_Medida { get; set; }
    //}

    //public partial class SA_LKP_MILITAR
    //{
    //    public int PK_MILITAR { get; set; }
    //    public string DE_MILITAR { get; set; }
    //    public Nullable<bool> Active { get; set; }
    //    public Nullable<int> Ordered { get; set; }
    //}

    //public partial class SA_LKP_MUNICIPIO_RESIDENCIA
    //{
    //    public short PK_Municipio { get; set; }
    //    public string DE_Municipio { get; set; }
    //    public Nullable<bool> Active { get; set; }
    //    public Nullable<int> Ordered { get; set; }
    //}

    //public partial class SA_LKP_PROBLEMA_JUSTICIA
    //{
    //    public byte PK_ProbJusticia { get; set; }
    //    public string DE_ProbJusticia { get; set; }
    //    public Nullable<bool> Active { get; set; }
    //    public Nullable<int> Ordered { get; set; }
    //}

    //public partial class SA_LKP_REFERIDOS_TX
    //{
    //    public byte PK_ReferidosTX { get; set; }
    //    public string DE_ReferidosTX { get; set; }
    //}

    //public partial class SA_LKP_SALUD_MENTAL
    //{
    //    public byte PK_SaludMental { get; set; }
    //    public string DE_SaludMental { get; set; }
    //    public string CO_TEDS_MH { get; set; }
    //    public Nullable<bool> Active { get; set; }
    //    public Nullable<int> Ordered { get; set; }
    //}

    //public partial class SA_LKP_TEDS_COND_LABORAL
    //{
    //    public byte PK_CondLaboral { get; set; }
    //    public string CO_TEDS { get; set; }
    //    public string DE_CondLaboral { get; set; }
    //    public string CO_TEDS_MH { get; set; }
    //    public Nullable<bool> Active { get; set; }
    //    public Nullable<int> Ordered { get; set; }
    //}

    //public partial class SA_LKP_TEDS_EPISODIO_PREVIO
    //{
    //    public byte PK_EpisodiosPrevios { get; set; }
    //    public string CO_TEDS { get; set; }
    //    public string DE_EpisodiosPrevios { get; set; }
    //    public Nullable<bool> Active { get; set; }
    //    public Nullable<int> Ordered { get; set; }
    //}

    //public partial class SA_LKP_TEDS_ESTADO_LEGAL
    //{
    //    public byte PK_EstadoLegal { get; set; }
    //    public string CO_TEDS { get; set; }
    //    public string DE_EstadoLegal { get; set; }
    //    public string CO_TEDS_MH { get; set; }
    //    public Nullable<bool> Active { get; set; }
    //    public Nullable<int> Ordered { get; set; }
    //}

    //public partial class SA_LKP_TEDS_ESTADO_MARITAL
    //{
    //    public byte PK_EstadoMarital { get; set; }
    //    public string CO_TEDS { get; set; }
    //    public string DE_EstadoMarital { get; set; }
    //    public string CO_TEDS_MH { get; set; }
    //    public Nullable<bool> Active { get; set; }
    //    public Nullable<int> Ordered { get; set; }
    //}

    //public partial class SA_LKP_TEDS_ETAPA_SERVICIO
    //{
    //    public byte PK_EtapaServicio { get; set; }
    //    public string CO_TEDS { get; set; }
    //    public string DE_EtapaServicio { get; set; }
    //    public string CO_TEDS_MH { get; set; }
    //    public Nullable<bool> Active { get; set; }
    //    public Nullable<int> Ordered { get; set; }
    //}

    //public partial class SA_LKP_TEDS_FRECUENCIA
    //{
    //    public byte PK_Frecuencia { get; set; }
    //    public string CO_TEDS { get; set; }
    //    public string DE_Frecuencia { get; set; }
    //    public string CO_TEDS_MH { get; set; }
    //    public Nullable<bool> Active { get; set; }
    //    public Nullable<int> Ordered { get; set; }
    //}

    //public partial class SA_LKP_TEDS_FRECUENCIA_AUTOAYUDA
    //{
    //    public byte PK_FreqAutoAyuda { get; set; }
    //    public string CO_TEDS { get; set; }
    //    public string DE_FreqAutoAyuda { get; set; }
    //    public string CO_TEDS_MH { get; set; }
    //    public Nullable<bool> Active { get; set; }
    //    public Nullable<int> Ordered { get; set; }
    //}

    //public partial class SA_LKP_TEDS_FUENTE_INGRESO
    //{
    //    public byte PK_FuenteIngreso { get; set; }
    //    public string CO_TEDS { get; set; }
    //    public string DE_FuenteIngreso { get; set; }
    //    public string CO_TEDS_HM { get; set; }
    //    public Nullable<bool> Active { get; set; }
    //    public Nullable<int> Ordered { get; set; }
    //}

    //public partial class SA_LKP_TEDS_GRADO
    //{
    //    public byte PK_Grado { get; set; }
    //    public string CO_TEDS { get; set; }
    //    public string DE_Grado { get; set; }
    //    public Nullable<bool> Active { get; set; }
    //    public Nullable<int> Ordered { get; set; }
    //    public string CO_TEDS_MH { get; set; }
    //}

    //public partial class SA_LKP_TEDS_NO_FUERZA_LABORAL
    //{
    //    public byte PK_NoFuerzaLaboral { get; set; }
    //    public string CO_TEDS { get; set; }
    //    public string DE_NoFuerzaLaboral { get; set; }
    //    public string CO_TEDS_MH { get; set; }
    //    public Nullable<bool> Active { get; set; }
    //    public Nullable<int> Ordered { get; set; }
    //}

    //public partial class SA_LKP_TEDS_PAGO
    //{
    //    public byte PK_Pago { get; set; }
    //    public string CO_TEDS { get; set; }
    //    public string DE_Pago { get; set; }
    //    public Nullable<bool> Active { get; set; }
    //    public Nullable<int> Ordered { get; set; }
    //    public string CO_TEDS_MH { get; set; }
    //}

    //public partial class SA_LKP_TEDS_RAZA
    //{
    //    public byte PK_Raza { get; set; }
    //    public string CO_TEDS { get; set; }
    //    public string DE_Raza { get; set; }
    //    public string CO_TEDS_MH { get; set; }
    //    public Nullable<bool> Active { get; set; }
    //    public Nullable<int> Ordered { get; set; }
    //}

    //public partial class SA_LKP_TEDS_REFERIDO
    //{
    //    public byte PK_Referido { get; set; }
    //    public string CO_TEDS { get; set; }
    //    public string DE_Referido { get; set; }
    //    public Nullable<bool> Active { get; set; }
    //    public Nullable<int> Ordered { get; set; }
    //}

    //public partial class SA_LKP_TEDS_RESIDENCIA
    //{
    //    public byte PK_Residencia { get; set; }
    //    public string CO_TEDS { get; set; }
    //    public string DE_Residencia { get; set; }
    //    public string CO_TEDS_MH { get; set; }
    //    public Nullable<bool> Active { get; set; }
    //    public Nullable<int> Ordered { get; set; }
    //}

    //public partial class SA_LKP_TEDS_SEGURO_SALUD
    //{
    //    public byte PK_SeguroSalud { get; set; }
    //    public string CO_TEDS { get; set; }
    //    public string DE_SeguroSalud { get; set; }
    //    public Nullable<bool> Active { get; set; }
    //    public Nullable<int> Ordered { get; set; }
    //    public string CO_TEDS_MH { get; set; }
    //}

    //public partial class SA_LKP_TEDS_SITUACION_ESCOLAR
    //{
    //    public byte PK_SituacionEscolar { get; set; }
    //    public string CO_TEDS { get; set; }
    //    public string DE_SituacionEscolar { get; set; }
    //}

    //public partial class SA_LKP_TEDS_SUSTANCIA
    //{
    //    public byte PK_Sustancia { get; set; }
    //    public string CO_TEDS { get; set; }
    //    public string DE_Sustancia { get; set; }
    //    public string CO_TEDS_Detalle { get; set; }
    //    public Nullable<bool> Active { get; set; }
    //    public Nullable<int> Ordered { get; set; }
    //    public string CO_TEDS_MH { get; set; }
    //    public string CO_TEDS_Detalle_MH { get; set; }
    //}

    //public partial class SA_LKP_TEDS_TIPO_ADMISION
    //{
    //    public byte PK_TipoAdmision { get; set; }
    //    public string CO_TEDS { get; set; }
    //    public string DE_TipoAdmision { get; set; }
    //}

    //public partial class SA_LKP_TEDS_VIA_UTILIZACION
    //{
    //    public byte PK_ViaUtilizacion { get; set; }
    //    public string CO_TEDS { get; set; }
    //    public string DE_ViaUtilizacion { get; set; }
    //    public string CO_TEDS_MH { get; set; }
    //    public Nullable<bool> Active { get; set; }
    //    public Nullable<int> Ordered { get; set; }
    //}

    //public partial class SA_LKP_TIEMPO_RESIDENCIA
    //{
    //    public byte PK_TiempoResidencia { get; set; }
    //    public string DE_TiempoResidencia { get; set; }
    //    public Nullable<bool> Active { get; set; }
    //    public Nullable<int> Ordered { get; set; }
    //}

    //public partial class SA_LKP_TIEMPO_ULT_TRAT
    //{
    //    public byte PK_TiempoUltTrat { get; set; }
    //    public string DE_TiempoUltTrat { get; set; }
    //    public Nullable<bool> Active { get; set; }
    //    public Nullable<int> Ordered { get; set; }
    //}

    //public partial class SA_NewData
    //{
    //    public int PK_ID { get; set; }
    //    public int FK_Perfil { get; set; }
    //    public Nullable<int> FK_Militar { get; set; }
    //    public Nullable<int> FK_FamMilitar { get; set; }
    //    public Nullable<int> FK_Genero { get; set; }
    //}

    //public partial class SA_PROGRAMA
    //{
    //    public short PK_Programa { get; set; }
    //    public byte FK_Administracion { get; set; }
    //    public Nullable<short> CO_Tipo { get; set; }
    //    public string CO_Programa { get; set; }
    //    public string CO_Prov_ID { get; set; }
    //    public string NB_Programa { get; set; }
    //    public string DE_Programa { get; set; }
    //    public string NB_ProgramaIngles { get; set; }
    //    public string CO_Hacienda { get; set; }
    //    public bool IN_Inactivo { get; set; }
    //    public bool IN_Creado_Fed { get; set; }
    //    public bool IN_TEDS { get; set; }
    //    public Nullable<bool> REP_TEDS { get; set; }
    //    public Nullable<bool> PREOW { get; set; }
    //    public Nullable<bool> IN_SUST { get; set; }
    //    public Nullable<bool> IN_INF_ANUAL { get; set; }
    //    public Nullable<bool> REP_TEDS_MH { get; set; }
    //    public Nullable<bool> IN_SELECCIONADO_REP { get; set; }
    //}

    //public partial class VW_EPISODIO
    //{
    //    public int PK_Episodio { get; set; }
    //    public int FK_Persona { get; set; }
    //    public short FK_Programa { get; set; }
    //    public string NB_Programa { get; set; }
    //    public Nullable<System.DateTime> FE_FechaConvenio { get; set; }
    //    public byte PK_Administracion { get; set; }
    //    public string NB_Administracion { get; set; }
    //    public System.DateTime FE_Episodio { get; set; }
    //    public byte FK_SeguroSalud { get; set; }
    //    public string DE_SeguroSalud { get; set; }
    //    public byte FK_FuentePago { get; set; }
    //    public string DE_Pago { get; set; }
    //    public byte FK_FeminaHijos { get; set; }
    //    public string DE_Femina { get; set; }
    //    public byte IN_VaronHijos { get; set; }
    //    public string DE_VaronHijos { get; set; }
    //    public byte FK_FuenteIngreso { get; set; }
    //    public string DE_FuenteIngreso { get; set; }
    //    public Nullable<byte> FK_IngresoIndividual { get; set; }
    //    public string DE_IngresoAnualIndividual { get; set; }
    //    public Nullable<byte> FK_IngresoFamiliar { get; set; }
    //    public string DE_IngresoAnualFamiliar { get; set; }
    //    public byte FK_TiempoResidencia { get; set; }
    //    public string DE_TiempoResidencia { get; set; }
    //    public short FK_Municipio { get; set; }
    //    public string DE_Municipio { get; set; }
    //    public byte IN_Zona { get; set; }
    //    public string DE_Zona { get; set; }
    //    public string NR_ZipCode { get; set; }
    //    public string DE_Barrio { get; set; }
    //    public byte FK_EtapaServicio { get; set; }
    //    public string DE_EtapaServicio { get; set; }
    //    public Nullable<byte> FK_NivelCuidadoSustancias { get; set; }
    //    public string DE_AbusoSustancias { get; set; }
    //    public Nullable<byte> FK_NivelCuidadoMental { get; set; }
    //    public string DE_SaludMental { get; set; }
    //    public byte IN_Metadona { get; set; }
    //    public string DE_Metadona { get; set; }
    //    public byte IN_CodDependiente { get; set; }
    //    public string DE_CodDependiente { get; set; }
    //    public Nullable<byte> IN_DiagnosticoDual { get; set; }
    //    public string DE_DiagnosticoDual { get; set; }
    //    public byte FK_FuenteReferido { get; set; }
    //    public string DE_Referido { get; set; }
    //    public byte FK_EstadoLegal { get; set; }
    //    public string DE_EstadoLegal { get; set; }
    //    public byte IN_ArrestadoAnteriormente { get; set; }
    //    public string DE_ArrestadoAnteriormente { get; set; }
    //    public Nullable<byte> NR_TotalArrestosPasado { get; set; }
    //    public byte FK_Justicia { get; set; }
    //    public string DE_ProbJusticia { get; set; }
    //    public Nullable<short> NR_DiasEsperaSustancias { get; set; }
    //    public byte FK_EpisodiosSustancias { get; set; }
    //    public string DE_EpisodiosPreviosSustancias { get; set; }
    //    public byte FK_DuracionSustancias { get; set; }
    //    public string DE_TiempoUltTratSustancias { get; set; }
    //    public Nullable<short> NR_DiasUltimaAltaSustancias { get; set; }
    //    public Nullable<short> NR_MesesUltimaAltaSustancias { get; set; }
    //    public byte FK_NivelCuidadoSustanciasAnterior { get; set; }
    //    public string DE_AbusoSustanciasAnterior { get; set; }
    //    public Nullable<byte> IN_SaludMental { get; set; }
    //    public string DE_IN_SaludMental { get; set; }
    //    public Nullable<short> NR_DiasEsperaMental { get; set; }
    //    public byte FK_EpisodiosMental { get; set; }
    //    public string DE_EpisodiosPreviosMental { get; set; }
    //    public byte FK_DuracionMental { get; set; }
    //    public string DE_TiempoUltTratMental { get; set; }
    //    public Nullable<short> NR_DiasUltimaAltaMental { get; set; }
    //    public Nullable<short> NR_MesesUltimaAltaMental { get; set; }
    //    public byte FK_NivelCuidadoMentalAnterior { get; set; }
    //    public string DE_SaludMentalAnterior { get; set; }
    //    public Nullable<byte> IN_AbusoSustancias { get; set; }
    //    public string DE_IN_AbusoSustancias { get; set; }
    //    public byte IN_ViolenciaDomestica { get; set; }
    //    public string DE_ViolenciaDomestica { get; set; }
    //    public byte IN_Maltrato { get; set; }
    //    public string DE_Maltrato { get; set; }
    //    public byte IN_TI_Maltrato { get; set; }
    //    public string DE_TI_Maltrato { get; set; }
    //    public string DE_Suicida { get; set; }
    //    public Nullable<byte> IN_TratadoMental { get; set; }
    //    public string DE_TratadoMental { get; set; }
    //    public Nullable<byte> IN_Ambulatorio { get; set; }
    //    public string DE_Ambulatorio { get; set; }
    //    public Nullable<byte> IN_HospitalizadoMental { get; set; }
    //    public string DE_HospitalizadoMental { get; set; }
    //    public Nullable<byte> IN_TI_Hospital { get; set; }
    //    public string DE_TI_Hospital { get; set; }
    //    public Nullable<byte> IN_TratamientoResidencial { get; set; }
    //    public string DE_TratamientoResidencial { get; set; }
    //    public Nullable<bool> ES_Episodio { get; set; }
    //    public string DE_ES_Episodio { get; set; }
    //    public Nullable<byte> IN_IdeaSuicida { get; set; }
    //    public string DE_IdeaSuicida { get; set; }
    //    public byte IN_Suicida { get; set; }
    //    public Nullable<System.DateTime> FE_Alta { get; set; }
    //}

    //public partial class VW_PERFIL
    //{
    //    public int PK_NR_Perfil { get; set; }
    //    public int FK_Episodio { get; set; }
    //    public System.DateTime FE_Perfil { get; set; }
    //    public string IN_TI_Perfil { get; set; }
    //    public string DE_DSMV_TrastornosClinicos1 { get; set; }
    //    public string DE_DSMV_TrastornosClinicos2 { get; set; }
    //    public string DE_DSMV_TrastornosClinicos3 { get; set; }
    //    public string CODE_DSMV_TrastornosClinicos1 { get; set; }
    //    public string CODE_DSMV_TrastornosClinicos2 { get; set; }
    //    public string CODE_DSMV_TrastornosClinicos3 { get; set; }
    //    public Nullable<int> FK_DSMV_TrastornosClinicos1 { get; set; }
    //    public Nullable<int> FK_DSMV_TrastornosClinicos2 { get; set; }
    //    public Nullable<int> FK_DSMV_TrastornosClinicos3 { get; set; }
    //    public string DE_DSMV_TrastornosPersonalidadRM1 { get; set; }
    //    public string DE_DSMV_TrastornosPersonalidadRM2 { get; set; }
    //    public string DE_DSMV_TrastornosPersonalidadRM3 { get; set; }
    //    public string CODE_DSMV_TrastornosPersonalidadRM1 { get; set; }
    //    public string CODE_DSMV_TrastornosPersonalidadRM2 { get; set; }
    //    public string CODE_DSMV_TrastornosPersonalidadRM3 { get; set; }
    //    public Nullable<int> FK_DSMV_TrastornosPersonalidadRM1 { get; set; }
    //    public Nullable<int> FK_DSMV_TrastornosPersonalidadRM2 { get; set; }
    //    public Nullable<int> FK_DSMV_TrastornosPersonalidadRM3 { get; set; }
    //    public string DE_DSMV_ProblemasPsicosocialesAmbientales1 { get; set; }
    //    public string DE_DSMV_ProblemasPsicosocialesAmbientales2 { get; set; }
    //    public string DE_DSMV_ProblemasPsicosocialesAmbientales3 { get; set; }
    //    public Nullable<int> FK_DSMV_ProblemasPsicosocialesAmbientales1 { get; set; }
    //    public Nullable<int> FK_DSMV_ProblemasPsicosocialesAmbientales2 { get; set; }
    //    public Nullable<int> FK_DSMV_ProblemasPsicosocialesAmbientales3 { get; set; }
    //    public Nullable<int> IN_DSMV_DiagnosticoDual { get; set; }
    //    public string NR_DSMV_FuncionamientoGlobal { get; set; }
    //    public string DE_DSMV_Comentarios { get; set; }
    //    public string DE_DSMV_OtrasObservaciones { get; set; }
    //    public string DE_DSMV_DiagnosticoDual { get; set; }
    //    public string DE_TI_Perfil { get; set; }
    //    public Nullable<byte> IN_Emancipado { get; set; }
    //    public string DE_Emancipado { get; set; }
    //    public byte FK_EstadoMarital { get; set; }
    //    public string DE_EstadoMarital { get; set; }
    //    public byte FK_CondicionLaboral { get; set; }
    //    public string DE_CondLaboral { get; set; }
    //    public byte FK_ActividadNoLaboral { get; set; }
    //    public string DE_NoFuerzaLaboral { get; set; }
    //    public Nullable<byte> IN_EmbarazosTratamiento { get; set; }
    //    public string DE_EmbarazosTratamiento { get; set; }
    //    public byte NR_Hijos { get; set; }
    //    public byte FK_Escolaridad { get; set; }
    //    public string DE_Grado { get; set; }
    //    public Nullable<System.DateTime> FE_UltimoInformeEscolar { get; set; }
    //    public Nullable<decimal> NR_PromedioAcademico { get; set; }
    //    public Nullable<short> NR_AusenciasAcad { get; set; }
    //    public Nullable<byte> IN_EducEspecial { get; set; }
    //    public string DE_EducEspecial { get; set; }
    //    public Nullable<byte> IN_DesertorEscolar { get; set; }
    //    public string DE_DesertorEscolar { get; set; }
    //    public byte FK_Familia { get; set; }
    //    public string DE_Familiar { get; set; }
    //    public byte NR_Familiar { get; set; }
    //    public byte FK_Residencia { get; set; }
    //    public string DE_Residencia { get; set; }
    //    public Nullable<byte> IN_ParticReunGrupos { get; set; }
    //    public string DE_ParticReunGrupos { get; set; }
    //    public Nullable<byte> FK_FreqAutoAyuda { get; set; }
    //    public string DE_FreqAutoAyuda { get; set; }
    //    public Nullable<byte> IN_Arrestado30dias { get; set; }
    //    public string DE_Arrestado30dias { get; set; }
    //    public Nullable<byte> NR_Arrestos30dias { get; set; }
    //    public Nullable<byte> IN_Arrestado365dias { get; set; }
    //    public string DE_Arrestado365dias { get; set; }
    //    public Nullable<byte> FK_CondicionPrimaria { get; set; }
    //    public string DE_DiagnosticoPrimario { get; set; }
    //    public Nullable<byte> FK_CondicionSecundaria { get; set; }
    //    public string DE_DiagnosticoSecundario { get; set; }
    //    public Nullable<byte> FK_CondicionTerciaria { get; set; }
    //    public string DE_DiagnosticoTerciaria { get; set; }
    //    public Nullable<short> FK_TrastornosClinicosPrimario { get; set; }
    //    public string DE_TipoAdmision { get; set; }
    //    public Nullable<int> FK_TipoAdmision { get; set; }
    //    public string DE_CategoriaCentroPrivado { get; set; }
    //    public Nullable<int> FK_CategoriaCentroPrivado { get; set; }
    //    public string DE_DSMIV_TCP { get; set; }
    //    public Nullable<short> FK_TrastornosClinicosSecundario { get; set; }
    //    public string DE_DSMIV_TCS { get; set; }
    //    public Nullable<short> FK_TrastornosClinicosTerciario { get; set; }
    //    public string DE_DSMIV_TCT { get; set; }
    //    public Nullable<short> FK_TrastornosPersonalidadPrimario { get; set; }
    //    public string DE_DSMIV_TPP { get; set; }
    //    public Nullable<short> FK_TrastornosPersonalidadSecundario { get; set; }
    //    public string DE_DSMIV_TPS { get; set; }
    //    public Nullable<short> FK_TrastornosPersonalidadTerciario { get; set; }
    //    public string DE_DSMIV_TPT { get; set; }
    //    public string CO_CondicionesMedicasPrimario { get; set; }
    //    public string CO_CondicionesMedicasSecundario { get; set; }
    //    public string CO_CondicionesMedicasTerciario { get; set; }
    //    public Nullable<byte> FK_ProblemasPsicosocialesPrimario { get; set; }
    //    public string DE_DSMIV_IV_P { get; set; }
    //    public Nullable<byte> FK_ProblemasPsicosocialesSecundario { get; set; }
    //    public string DE_DSMIV_IV_S { get; set; }
    //    public Nullable<byte> FK_ProblemasPsicosocialesTerciario { get; set; }
    //    public string DE_DSMIV_IV_T { get; set; }
    //    public Nullable<int> NR_EscalaGAF { get; set; }
    //    public Nullable<byte> FK_ReferidosGeneradosTX { get; set; }
    //    public string DE_ReferidosTX { get; set; }
    //    public Nullable<byte> FK_DisposicionFinalReferido { get; set; }
    //    public string DE_DisposicionFinal { get; set; }
    //    public byte FK_DrogaPrimario { get; set; }
    //    public string DE_Droga_P { get; set; }
    //    public byte FK_DrogaSecundario { get; set; }
    //    public string DE_Droga_S { get; set; }
    //    public byte FK_DrogaTerciario { get; set; }
    //    public string DE_Droga_T { get; set; }
    //    public byte FK_ViaPrimario { get; set; }
    //    public string DE_Via_P { get; set; }
    //    public byte FK_ViaSecundario { get; set; }
    //    public string DE_Via_S { get; set; }
    //    public byte FK_ViaTerciario { get; set; }
    //    public string DE_Via_T { get; set; }
    //    public byte FK_FrecuenciaPrimario { get; set; }
    //    public string DE_Frecuencia_P { get; set; }
    //    public byte FK_FrecuenciaSecundario { get; set; }
    //    public string DE_Frecuencia_S { get; set; }
    //    public byte FK_FrecuenciaTerciario { get; set; }
    //    public string DE_Frecuencia_T { get; set; }
    //    public Nullable<byte> IN_EdadInicioPrimario { get; set; }
    //    public Nullable<byte> IN_EdadInicioSecundario { get; set; }
    //    public Nullable<byte> IN_EdadInicioTerciario { get; set; }
    //    public Nullable<byte> NR_CantidadPrimario { get; set; }
    //    public Nullable<byte> NR_CantidadSecundario { get; set; }
    //    public Nullable<byte> NR_CantidadTerciario { get; set; }
    //    public Nullable<byte> FK_MedidaPrimario { get; set; }
    //    public string DE_Medida_P { get; set; }
    //    public Nullable<int> FK_SituacionEscolar { get; set; }
    //    public string DE_SituacionEscolar { get; set; }
    //    public Nullable<byte> FK_MedidaSecundario { get; set; }
    //    public string DE_Medida_S { get; set; }
    //    public Nullable<byte> FK_MedidaTerciario { get; set; }
    //    public string DE_Medida_T { get; set; }
    //    public Nullable<decimal> NR_GastoPrimario { get; set; }
    //    public Nullable<decimal> NR_GastoSecundario { get; set; }
    //    public Nullable<decimal> NR_GastoTerciario { get; set; }
    //    public Nullable<decimal> NR_PromedioVisitas { get; set; }
    //    public Nullable<byte> FK_Alta { get; set; }
    //    public string DE_Alta { get; set; }
    //    public Nullable<short> FK_CentroTraslado { get; set; }
    //    public string NB_Programa { get; set; }
    //    public string DE_Comentario { get; set; }
    //    public string TI_Transaccion { get; set; }
    //    public string DE_Transaccion { get; set; }
    //    public System.Guid FK_Sesion { get; set; }
    //    public string TI_Edicion { get; set; }
    //    public string DE_Edicion { get; set; }
    //    public System.DateTime FE_Edicion { get; set; }
    //    public Nullable<bool> ES_Perfil { get; set; }
    //    public string DE_SaludMental { get; set; }
    //    public string DE_AbusoSustancias { get; set; }
    //    public string NB_ProgramaActual { get; set; }
    //    public string NB_AdministracionActual { get; set; }
    //    public Nullable<byte> IN_EstLeg { get; set; }
    //    public string DE_EstLeg { get; set; }
    //    public Nullable<System.DateTime> FE_Contacto { get; set; }
    //    public int FK_Persona { get; set; }
    //}

    //public partial class VW_PERSONA
    //{
    //    public int PK_Persona { get; set; }
    //    public string NR_SeguroSocial { get; set; }
    //    public byte FK_Sexo { get; set; }
    //    public string DE_Sexo { get; set; }
    //    public string AP_Primero { get; set; }
    //    public string AP_Segundo { get; set; }
    //    public string NB_Primero { get; set; }
    //    public string NB_Segundo { get; set; }
    //    public System.DateTime FE_Nacimiento { get; set; }
    //    public Nullable<int> NR_Edad { get; set; }
    //    public byte FK_Veterano { get; set; }
    //    public string DE_Veterano { get; set; }
    //    public byte FK_GrupoEtnico { get; set; }
    //    public string DE_GrupoEtnico { get; set; }
    //    public System.Guid FK_Sesion { get; set; }
    //    public string TI_Edicion { get; set; }
    //    public System.DateTime FE_Edicion { get; set; }
    //}

    //public partial class SPR_PERFILES_LEY22_Result
    //{
    //    public int PK_NR_Perfil { get; set; }
    //    public System.DateTime FE_Perfil { get; set; }
    //    public string TI_Perfil { get; set; }
    //    public string URL { get; set; }
    //}
}