//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;
namespace Ley22_WebApp_V2.AppCode
{
    //public partial class SEPSEntities1 : DbContext
    //{
    //    public SEPSEntities1()
    //        : base("name=SEPSEntities1")
    //    {
    //    }

    //    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    //    {
    //        throw new UnintentionalCodeFirstException();
    //    }

    //    public virtual DbSet<SA_LKP_ABUSO_SUSTANCIAS> SA_LKP_ABUSO_SUSTANCIAS { get; set; }
    //    public virtual DbSet<SA_LKP_ALTA> SA_LKP_ALTA { get; set; }
    //    public virtual DbSet<SA_LKP_COMPOSICION_FAMILIAR> SA_LKP_COMPOSICION_FAMILIAR { get; set; }
    //    public virtual DbSet<SA_LKP_DIAGNOSTICO> SA_LKP_DIAGNOSTICO { get; set; }
    //    public virtual DbSet<SA_LKP_DSMIV_CAT> SA_LKP_DSMIV_CAT { get; set; }
    //    public virtual DbSet<SA_LKP_DSMIV_IV> SA_LKP_DSMIV_IV { get; set; }
    //    public virtual DbSet<SA_LKP_DSMV> SA_LKP_DSMV { get; set; }
    //    public virtual DbSet<SA_LKP_DSMV_ProblemasPsicosocialesAmbientales> SA_LKP_DSMV_ProblemasPsicosocialesAmbientales { get; set; }
    //    public virtual DbSet<SA_LKP_FEMINA> SA_LKP_FEMINA { get; set; }
    //    public virtual DbSet<SA_LKP_INGRESO_ANUAL> SA_LKP_INGRESO_ANUAL { get; set; }
    //    public virtual DbSet<SA_LKP_MEDIDA> SA_LKP_MEDIDA { get; set; }
    //    public virtual DbSet<SA_LKP_MUNICIPIO_RESIDENCIA> SA_LKP_MUNICIPIO_RESIDENCIA { get; set; }
    //    public virtual DbSet<SA_LKP_PROBLEMA_JUSTICIA> SA_LKP_PROBLEMA_JUSTICIA { get; set; }
    //    public virtual DbSet<SA_LKP_REFERIDOS_TX> SA_LKP_REFERIDOS_TX { get; set; }
    //    public virtual DbSet<SA_LKP_SALUD_MENTAL> SA_LKP_SALUD_MENTAL { get; set; }
    //    public virtual DbSet<SA_LKP_TEDS_COND_LABORAL> SA_LKP_TEDS_COND_LABORAL { get; set; }
    //    public virtual DbSet<SA_LKP_TEDS_EPISODIO_PREVIO> SA_LKP_TEDS_EPISODIO_PREVIO { get; set; }
    //    public virtual DbSet<SA_LKP_TEDS_ESTADO_LEGAL> SA_LKP_TEDS_ESTADO_LEGAL { get; set; }
    //    public virtual DbSet<SA_LKP_TEDS_ESTADO_MARITAL> SA_LKP_TEDS_ESTADO_MARITAL { get; set; }
    //    public virtual DbSet<SA_LKP_TEDS_ETAPA_SERVICIO> SA_LKP_TEDS_ETAPA_SERVICIO { get; set; }
    //    public virtual DbSet<SA_LKP_TEDS_FRECUENCIA> SA_LKP_TEDS_FRECUENCIA { get; set; }
    //    public virtual DbSet<SA_LKP_TEDS_FRECUENCIA_AUTOAYUDA> SA_LKP_TEDS_FRECUENCIA_AUTOAYUDA { get; set; }
    //    public virtual DbSet<SA_LKP_TEDS_FUENTE_INGRESO> SA_LKP_TEDS_FUENTE_INGRESO { get; set; }
    //    public virtual DbSet<SA_LKP_TEDS_GRADO> SA_LKP_TEDS_GRADO { get; set; }
    //    public virtual DbSet<SA_LKP_TEDS_NO_FUERZA_LABORAL> SA_LKP_TEDS_NO_FUERZA_LABORAL { get; set; }
    //    public virtual DbSet<SA_LKP_TEDS_PAGO> SA_LKP_TEDS_PAGO { get; set; }
    //    public virtual DbSet<SA_LKP_TEDS_RAZA> SA_LKP_TEDS_RAZA { get; set; }
    //    public virtual DbSet<SA_LKP_TEDS_REFERIDO> SA_LKP_TEDS_REFERIDO { get; set; }
    //    public virtual DbSet<SA_LKP_TEDS_RESIDENCIA> SA_LKP_TEDS_RESIDENCIA { get; set; }
    //    public virtual DbSet<SA_LKP_TEDS_SEGURO_SALUD> SA_LKP_TEDS_SEGURO_SALUD { get; set; }
    //    public virtual DbSet<SA_LKP_TEDS_SITUACION_ESCOLAR> SA_LKP_TEDS_SITUACION_ESCOLAR { get; set; }
    //    public virtual DbSet<SA_LKP_TEDS_SUSTANCIA> SA_LKP_TEDS_SUSTANCIA { get; set; }
    //    public virtual DbSet<SA_LKP_TEDS_TIPO_ADMISION> SA_LKP_TEDS_TIPO_ADMISION { get; set; }
    //    public virtual DbSet<SA_LKP_TEDS_VIA_UTILIZACION> SA_LKP_TEDS_VIA_UTILIZACION { get; set; }
    //    public virtual DbSet<SA_LKP_TIEMPO_RESIDENCIA> SA_LKP_TIEMPO_RESIDENCIA { get; set; }
    //    public virtual DbSet<SA_LKP_TIEMPO_ULT_TRAT> SA_LKP_TIEMPO_ULT_TRAT { get; set; }
    //    public virtual DbSet<SA_PROGRAMA> SA_PROGRAMA { get; set; }
    //    public virtual DbSet<VW_EPISODIO> VW_EPISODIO { get; set; }
    //    public virtual DbSet<VW_PERFIL> VW_PERFIL { get; set; }
    //    public virtual DbSet<VW_PERSONA> VW_PERSONA { get; set; }
    //    public virtual DbSet<SA_LKP_GENERO> SA_LKP_GENERO { get; set; }
    //    public virtual DbSet<SA_LKP_MILITAR> SA_LKP_MILITAR { get; set; }
    //    public virtual DbSet<SA_NewData> SA_NewData { get; set; }

    //    public virtual ObjectResult<SPR_PERFILES_LEY22_Result> SPR_PERFILES_LEY22(Nullable<int> pK_Episodio)
    //    {
    //        var pK_EpisodioParameter = pK_Episodio.HasValue ?
    //            new ObjectParameter("PK_Episodio", pK_Episodio) :
    //            new ObjectParameter("PK_Episodio", typeof(int));

    //        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPR_PERFILES_LEY22_Result>("SPR_PERFILES_LEY22", pK_EpisodioParameter);
    //    }
    //}
}
