//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ley22_WebApp_V2.Old_App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class Precio
    {
        public int Id_Precio { get; set; }
        public string Descripcion { get; set; }
        public decimal Cantidad { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Activo { get; set; }
    }
}
