//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ley22_WebApp_V2.Old_App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class SA_LKP_TEDS_FUENTE_INGRESO
    {
        public byte PK_FuenteIngreso { get; set; }
        public string CO_TEDS { get; set; }
        public string DE_FuenteIngreso { get; set; }
        public string CO_TEDS_HM { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> Ordered { get; set; }
    }
}
