//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ley22_WebApp_V2.Old_App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class SA_NewData
    {
        public int PK_ID { get; set; }
        public int FK_Perfil { get; set; }
        public Nullable<int> FK_Militar { get; set; }
        public Nullable<int> FK_FamMilitar { get; set; }
        public Nullable<int> FK_Genero { get; set; }
    }
}
