//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ley22_WebApp_V2.Old_App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class SA_USUARIO_PERMISO_Mapping
    {
        public int FK_Usuario { get; set; }
        public int FK_Permiso { get; set; }
        public int FK_Programa { get; set; }
    }
}
