//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ley22_WebApp_V2.Old_App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tribunal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tribunal()
        {
            this.CasoCriminals = new HashSet<CasoCriminal>();
        }
    
        public int Id_Tribunal { get; set; }
        public string NB_Tribunal { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public int FK_Categoria { get; set; }
        public int FK_Region { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CasoCriminal> CasoCriminals { get; set; }
    }
}
